### ISSUE TITLE
The `test_online_qasm_simulator_two_registers` is failing in master

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#1016]
### What is the current behavior?
The test is failing in the `master` branch with the following error:

```
======================================================================
FAIL: test_online_qasm_simulator_two_registers (python.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test online_qasm_simulator_two_registers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Qiskit/qiskit-terra/test/python/common.py", line 373, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/home/travis/build/Qiskit/qiskit-terra/test/python/ibmq/test_ibmq_qasm_simulator.py", line 109, in test_online_qasm_simulator_two_registers
    self.assertEqual(result1, {'00 01': 1024})
AssertionError: {'01 00': 1024} != {'00 01': 1024}
- {'01 00': 1024}
?     ---

+ {'00 01': 1024}
?    +++
```

### Steps to reproduce the problem
The failure is intermittent. It seems related with running all the test suite. When running isolated, it seems not to be failing.

### What is the expected behavior?
The test should pass regardless of other tests.

### Suggested solutions
It will be temporally marked as an expected failure but we should dig into what happens.

**Comment by nonhermitian** [comment]
It finally failed for me locally in the tests. However, I ran the test 1000 times by itself and could not reproduce it

**Comment by jaygambetta** [comment]
opening again as still failing
