### ISSUE TITLE
`QuantumCircuit.draw()` cannot produce pdf successfully using `'latex'` mode

### ISSUE THREAD

**Issue by JoshuaLau0220** [Qiskit/qiskit-terra#10211]
### Environment

- **Qiskit Terra version**: 0.22.2
- **Python version**: 3.9.15
- **Operating system**: Ubuntu 22.04.2 LTS

### What is happening?

Upon calling `QuantumCircuit.draw('latex', 'out.pdf')`, `qiskit` fails to produce a pdf output with latex mode. The bug seems to occur not when compiling the pdf, but when qiskit tries to move the pdf from the temporary folder to the target directory.

I've looked around on the Internet and found out that this might be a bug due to `os.rename(...)`. ([Ref](https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link))
It seems to due to that `os.rename(...)` cannot handle moving files between filesystems. 

### How can we reproduce the issue?

I've used the following snippet, substituting `<path_to_qasm_file>` to any qasm filepath.
```
from qiskit import QuantumCircuit
qc = QuantumCircuit.from_qasm_file(<path_to_qasm_file>)
qc.draw('latex', filename='out.pdf') # error happens here
```
The bug though is probably related to filesystems of the device, so it may work just fine on other computers.

### What should happen?

The following traceback is produced:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<redacted_for_privacy>/qiskit/circuit/quantumcircuit.py", line 1957, in draw
    return circuit_drawer(
  File "/<redacted_for_privacy>/qiskit/visualization/circuit/circuit_visualization.py", line 233, in circuit_drawer
    image = _latex_circuit_drawer(
  File "/<redacted_for_privacy>/qiskit/utils/lazy_tester.py", line 149, in out
    return function(*args, **kwargs)
  File "/<redacted_for_privacy>/qiskit/utils/lazy_tester.py", line 149, in out
    return function(*args, **kwargs)
  File "/<redacted_for_privacy>/qiskit/utils/lazy_tester.py", line 149, in out
    return function(*args, **kwargs)
  File "/<redacted_for_privacy>/qiskit/visualization/circuit/circuit_visualization.py", line 491, in _latex_circuit_drawer
    os.rename(base + ".pdf", filename)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp8gx5xtqi/circuit.pdf' -> 'out.pdf'
```
No pdf is outputted. Or more precisely, the pdf is created, but not moved to the target directory, and then the temporary folder is deleted.

### Any suggestions?

Currently, if I change `qiskit/visualization/circuit/circuit_visualization.py", line 491` from
```
os.rename(base + ".pdf", filename)
```
to
```
import shutil
shutil.move(base + ".pdf", filename)
```
then it seems to work just fine.

**Comment by jakelishman** [comment]
Thanks for the report!  I believe we fixed this in #8629 - could you check that the bug persists if you upgrade your version of Terra?

**Comment by jakelishman** [comment]
Ah, no, it looks like somehow we regressed after that fix was made, sorry.  It's pretty hard to test, so we might not have noticed it. Would you like to make a PR making the change you suggest.

**Comment by JoshuaLau0220** [comment]
Of course! I've filed my fix in this PR: #10212.
