### ISSUE TITLE
Bug in serialization of subclass

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-terra#10577]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

When creating a subclass of a `PauliGate`, it does not serialize correctly.
See example below. This was originally opened as an issue in `qiskit-ibm-provider`: 
https://github.com/Qiskit/qiskit-ibm-provider/issues/690.

### How can we reproduce the issue?

```
import io
from qiskit import QuantumCircuit
from qiskit.circuit.library import PauliGate
from qiskit.qpy import dump, load

def check_serialization(circuit):
    # dump and load
    qpy_file = io.BytesIO()
    dump(circuit, qpy_file)
    qpy_file.seek(0)
    new_circuit = load(qpy_file)[0]

class ChildPauliGate(PauliGate):
    """Trivial subclass of PauliGate"""
    pass

# Subclass PauliGate
circ = QuantumCircuit(2)
circ.append(ChildPauliGate("XX"), [0, 1])
circ.measure_all()
check_serialization(circ)
```
This fails with the following message:
```
Traceback (most recent call last):
  File "/home/merav/work/qiskit_ibm_provider/json_bug/../tests/json_bug_terra.py", line 21, in <module>
    check_serialization(circ)
  File "/home/merav/work/qiskit_ibm_provider/json_bug/../tests/json_bug_terra.py", line 11, in check_serialization
    new_circuit = load(qpy_file)[0]
  File "/home/merav/work/terra/terra-main/qiskit/qpy/interface.py", line 269, in load
    loader(
  File "/home/merav/work/terra/terra-main/qiskit/qpy/binary_io/circuits.py", line 1089, in read_circuit
    _read_instruction(file_obj, circ, out_registers, custom_operations, version, vectors)
  File "/home/merav/work/terra/terra-main/qiskit/qpy/binary_io/circuits.py", line 252, in _read_instruction
    inst_obj = _parse_custom_operation(
  File "/home/merav/work/terra/terra-main/qiskit/qpy/binary_io/circuits.py", line 342, in _parse_custom_operation
    inst_obj = Gate(gate_name, num_qubits, params)
  File "/home/merav/work/terra/terra-main/qiskit/circuit/gate.py", line 37, in __init__
    super().__init__(name, num_qubits, 0, params, label=label)
  File "/home/merav/work/terra/terra-main/qiskit/circuit/instruction.py", line 105, in __init__
    self.params = params  # must be at last (other properties may be required for validation)
  File "/home/merav/work/terra/terra-main/qiskit/circuit/instruction.py", line 223, in params
    self._params.append(self.validate_parameter(single_param))
  File "/home/merav/work/terra/terra-main/qiskit/circuit/gate.py", line 235, in validate_parameter
    raise CircuitError(f"Invalid param type {type(parameter)} for gate {self.name}.")
qiskit.circuit.exceptions.CircuitError: "Invalid param type <class 'str'> for gate pauli."

```

### What should happen?

Should work correctly.

### Any suggestions?

The method `_write_instruction` defines:
```
gate_class_name = instruction.operation.__class__.__name__
```
Perhaps it should be taking 
```
gate_class_name = instruction.operation.__name__ ?
```

**Comment by mtreinish** [comment]
The problem here is a conflict between the `Gate` class and the params list for `PauliGate`. What qpy does in the case of custom gate classes (that are defined outside of `qiskit`) is it stores a custom instance of `Gate` with the `definition`, name, number of qubits, and params copied over from the custom class. This is done because for deserialization there is no guarantee that the custom definition will be available on the other side (the class might not be defined, it might be completely different, etc). However, in this case because it's a subclass of `PauliGate` the params are strings which is a valid type for `PauliGate`'s constructor, but not for a `Gate` object.  This is fundamentally an issue with the data model of `Gate`/`Instruction`'s inheritance around parameter type validation (where it allows the parent to be more restrictive than the child class). I'm not sure there is fix that will allow the `PauliGate` subclass to be serialized as it's built there short of changing that. If you overrode the `params` of `ChildPauliGate` not be the pauli labels then (with a fix to #8941) the serialization will work as expected as a gate named `pauli` with the same definition will exist in the circuit.

**Comment by gadial** [comment]
This issue is still valid in Qiskit 2.4. However, as Matthew said, I don't think it's something that can or should be fixed as part of QPY, which correctly serializes and deserializes the data; rather, it's a problem with the `Gate` data model and the custom gate mechanism in Python (which should hopefully be less ill-posed once we switch to rust-based custom gates).

**Comment by jakelishman** [comment]
Arguably the fix here would be for QPY to reload custom instructions as some `qpy.DeserializedInstruction` and `qpy.DeserializedGate`, which both skip the params "type" validation - if it was valid for the incoming data model, we should preserve it for loading.

That said, I think in practice the bug is less likely to appear in practice, because the primary user of QPY (the IBM backends) now require pre-transpiled gates.

**Comment by mtreinish** [comment]
We shouldn't overfit on IBM's API usage of qpy. By volume of usage it is by far the largest user of qpy, but the format is not exclusively for that purpose and as you point out the usage by the IBM service is very constrained. This is a bug in deserialization and we should fix it.

Defining a custom deserialization gate class is a good idea and would let us workaround these kind of issues where a parameter is serializable and constructed but outside the allowed parameter types on the base `Gate` that we're normalizing on for deserialization of custom gates. It's a good balance because it doesn't open up the arbitrary code issues with arbitrary user defined custom gates but gives us more flexibility than we have now.
