### ISSUE TITLE
QPY loses scheduling information

### ISSUE THREAD

**Issue by apateonas** [Qiskit/qiskit-terra#10582]
### Environment

- **Qiskit Terra version**: 0.24.1
- **Python version**: 3.10.12
- **Operating system**: mac OS 13.5

### What is happening?

I want to generate a dataset of scheduled Quantum Circuits to run analysis on. I want to save these circuits to a file, so I found the `qpy` functionality qiskit provides to write circuits to bytes. However, I am seeing that when I load the circuit from the bytes, I am losing scheduling information. Specifically, I can use timeline_drawer before I write to bytes, but when I load the circuit back, I get `VisualizationError: 'Input circuit bv is not scheduled and it contains operations with unknown delays. This cannot be visualized.'` The circuit`op_start_times`, qubit start/end times are also undefined.

### How can we reproduce the issue?

```
import io
from qiskit import qpy, compiler
from qiskit.circuit.library import QFT
from qiskit.providers.fake_provider import FakeProviderForBackendV2


def to_bytes(circuit: QuantumCircuit):
    buf = io.BytesIO()
    qpy.dump(circuit, buf)
    val = buf.getvalue()
    buf.close()
    return val


def from_bytes(qpy_bytes):
    buf = io.BytesIO(qpy_bytes)
    circuit = qpy.load(buf)[0]
    buf.close()
    return circuit


# Build circuit
circuit = QFT(
    name="qft",
    num_qubits=7,
    approximation_degree=0,
    do_swaps=True,
    inverse=False,
    insert_barriers=False,
)
provider = FakeProviderForBackendV2()
backend = provider.get_backend("fake_perth")
transpiled = compiler.transpile(
    circuit,
    backend=backend,
    optimization_level=3,
    seed_transpiler=0,
    layout_method="sabre",
    routing_method="sabre",
    scheduling_method="alap",
)

# Dump and load from Bytes with QPY
circuit_bytes = to_bytes(transpiled)
loaded_circuit = from_bytes(circuit_bytes)

print(transpiled.op_start_times)
print(loaded_circuit.op_start_times)
```

### What should happen?

QPY serialization should not lose any information in the `QuantumCircuit`, including any scheduling details.

**Comment by Abhiraj-Shrotriya** [comment]
@jakelishman @apateonas 

 **I would like to have a look at this bug. Can you please assign me?**

**Thank you**

And, a simpler and error-free way of reproducing this issue would be as follows:

```
import io
from qiskit import qpy, transpile, QuantumCircuit
from qiskit.providers.fake_provider import FakePerth

def to_bytes(circuit):
    buf = io.BytesIO()
    qpy.dump(circuit, buf)
    val = buf.getvalue()
    buf.close()
    return val

def from_bytes(qpy_bytes):
    buf = io.BytesIO(qpy_bytes)
    circuit = qpy.load(buf)[0]
    buf.close()
    return circuit

# Build circuit
quantum_circuit = QuantumCircuit(4, 2)
quantum_circuit.x(0)

backend = FakePerth()
transpiled_circuit = transpile(
    quantum_circuit,
    backend=backend,
    optimization_level=2,
    seed_transpiler=0,
    scheduling_method="alap",
)

# Dump and load from Bytes with QPY
circuit_bytes = to_bytes(transpiled_circuit)
loaded_circuit = from_bytes(circuit_bytes)

print(transpiled_circuit.op_start_times)
print(loaded_circuit.op_start_times)
```

**Comment by jakelishman** [comment]
@Abhiraj-Shrotriya, you're welcome to have a look, but just be warned that it's quite possible that this issue will not be simple, if there's significant changes to QPY serialisation required.  I think / hope that that's not the case, but it could be quite a significant chunk of work.

**Comment by Abhiraj-Shrotriya** [comment]
@jakelishman,
Hi, I took a look at it. Yes, this fix will take some time. I will try my best to solve this as soon as possible.
If required, of course I will take your reviews.
Thank you

**Comment by gadial** [comment]
This issue is still valid in Qiskit 2.4. It can be reproduced with the following code
```
import io
from qiskit import qpy, compiler
from qiskit.circuit.library import QFTGate
from qiskit_ibm_runtime.fake_provider import FakePerth
from qiskit import QuantumCircuit

def to_bytes(circuit: QuantumCircuit):
    buf = io.BytesIO()
    qpy.dump(circuit, buf)
    val = buf.getvalue()
    buf.close()
    return val


def from_bytes(qpy_bytes):
    buf = io.BytesIO(qpy_bytes)
    circuit = qpy.load(buf)[0]
    buf.close()
    return circuit


# Build circuit
circuit = QuantumCircuit(7)
gate = QFTGate(num_qubits=7)
circuit.append(gate, range(7))
backend = FakePerth()
transpiled = compiler.transpile(
    circuit,
    backend=backend,
    optimization_level=3,
    seed_transpiler=0,
    layout_method="sabre",
    routing_method="sabre",
    scheduling_method="alap",
)

# Dump and load from Bytes with QPY
circuit_bytes = to_bytes(transpiled)
loaded_circuit = from_bytes(circuit_bytes)

print(transpiled.op_start_times)
print(loaded_circuit.op_start_times)
```

Which results in
```
[0, 0, 0, 160, 160, 2080, 2080, 4000, 16832, 16832, 16992, 0, 4000, 6880, 6880, 9760, 20672, 0, 9760, 11264, 12928, 15488, 12928, 0, 0, 12928, 14208, 14208, 15488, 16992, 16992, 18912, 20672, 29760, 20672, 20672, 23552, 23552, 26432, 36192, 36192, 36352, 16992, 15488, 22272, 22272, 23712, 24992, 26432, 28096, 28096, 29760, 31680, 41952, 29760, 31680, 31680, 33184, 34848, 36352, 39072, 39072, 41792, 41792, 41952, 41952, 43872, 45632, 47552, 52992, 41792, 47552, 50272, 50272, 52992, 52992, 54752, 54752, 56512, 56512, 56512, 56672, 52992, 36352, 52352, 52352, 52512, 26432, 32480, 0, 32480, 35360, 35360, 38240, 41056, 41056, 43872, 65024, 65024, 65184, 38240, 43872, 43872, 46752, 49472, 52352, 52352, 52512, 52512, 53792, 53952, 53792, 53952, 53952, 55232, 55232, 55392, 55392, 56672, 56672, 58336, 59840, 61504, 64224, 64224, 66944, 66944, 68704, 68704, 70464, 70464, 66944, 61504, 70464, 70464, 71968, 71968, 73472, 77312, 77312, 77472, 56672, 65024, 65024, 65184, 67840, 68000, 67840, 68000, 68000, 70656, 70656, 70816, 70816, 73472, 102304, 73472, 73472, 74752, 76192, 77472, 79136, 80640, 82304, 85024, 85024, 87744, 87744, 89504, 89504, 91264, 91264, 87744, 82304, 91264, 92768, 94432, 95936, 98816, 77472, 95936, 95936, 97376, 97376, 98816, 98816, 100480, 100480, 102144, 102144, 102144, 102304, 98816, 52352]
Traceback (most recent call last):
  File "/home/gadial/Workspaces/qiskit_qpy/scratch.py", line 42, in <module>
    print(loaded_circuit.op_start_times)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gadial/Workspaces/qiskit_qpy/qiskit/circuit/quantumcircuit.py", line 1516, in op_start_times
    raise AttributeError(
AttributeError: This circuit is not scheduled. To schedule it run the circuit through one of the transpiler scheduling passes.. Did you mean: '_op_start_times'?
```

I did not take an in-depth look at the problem yet, but in a glance I guess this cannot be fixed without an update to the QPY format, possibly as part of the QPY18 update (https://github.com/Qiskit/qiskit/issues/15524). It is currently not listed in the checklist for that update and we need to decide whether we want to implement this.
