### ISSUE TITLE
Call to plot_bloch_vector(bloch) results in "TypeError: __call__() takes 1 positional argument but 2 were given"

### ISSUE THREAD

**Issue by rajeshn76** [Qiskit/qiskit-terra#1090]
### Information

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6
- **Operating system**: Mac OSX 10.12.6 (Sierra)

### What is the current behavior?
I tried to run the sample code for Bloch Sphere ("quantum_phase_bloch.py"), from this tutorial:

https://quantumexperience.ng.bluemix.net/proxy/tutorial/full-user-guide/002-The_Weird_and_Wonderful_World_of_the_Qubit/005-The_Bloch_Sphere.html

Executing the code results in the following error:

Traceback (most recent call last):
  File "/Users/rajeshn76/python/projects/helloworld/quantum_phase_bloch.py", line 60, in <module>
    plot_bloch_vector(bloch, "my bloch")
  File "/Users/rajeshn76/Library/Python/3.6/lib/python/site-packages/qiskit/tools/visualization/_state_visualization.py", line 53, in plot_bloch_vector
    B.show(title=title)
  File "/Users/rajeshn76/Library/Python/3.6/lib/python/site-packages/qiskit/tools/visualization/bloch.py", line 585, in show
    plt.show(self.fig)
  File "/Users/rajeshn76/Library/Python/3.6/lib/python/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
TypeError: __call__() takes 1 positional argument but 2 were given

### Steps to reproduce the problem
Run the sample code for Bloch Sphere ("quantum_phase_bloch.py"), from this tutorial.
https://quantumexperience.ng.bluemix.net/proxy/tutorial/full-user-guide/002-The_Weird_and_Wonderful_World_of_the_Qubit/005-The_Bloch_Sphere.html

# quantum_phase_bloch.py
import numpy as np

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute
from qiskit.tools.visualization import plot_bloch_vector

# Define the Quantum and Classical Registers
q = QuantumRegister(1)
c = ClassicalRegister(1)

# Build the circuits
pre = QuantumCircuit(q, c)
pre.h(q)
pre.barrier()

meas_x = QuantumCircuit(q, c)
meas_x.barrier()
meas_x.h(q)
meas_x.measure(q, c)

meas_y = QuantumCircuit(q, c)
meas_y.barrier()
meas_y.s(q).inverse()
meas_y.h(q)
meas_y.measure(q, c)

meas_z = QuantumCircuit(q, c)
meas_z.barrier()
meas_z.measure(q, c)

bloch_vector = ['x', 'y', 'z']
exp_vector = range(0, 21)
circuits = []
for exp_index in exp_vector:
    middle = QuantumCircuit(q, c)
    phase = 2*np.pi*exp_index/(len(exp_vector)-1)
    middle.u1(phase, q)
    circuits.append(pre + middle + meas_x)
    circuits.append(pre + middle + meas_y)
    circuits.append(pre + middle + meas_z)
    
# Execute the circuit
job = execute(circuits, backend = 'local_qasm_simulator', shots=1024)
result = job.result()

# Plot the result
for exp_index in exp_vector:
    bloch = [0, 0, 0]
    for bloch_index in range(len(bloch_vector)):
        data = result.get_counts(circuits[3*exp_index+bloch_index])
        try:
            p0 = data['0']/1024.0
        except KeyError:
            p0 = 0
        try:
            p1 = data['1']/1024.0
        except KeyError:
            p1 = 0
        bloch[bloch_index] = p0-p1
    plot_bloch_vector(bloch)

### What is the expected behavior?
Should plot the Bloch Sphere for visualizing the quantum states generated by the sample code.

### Suggested solutions
The bug is in "bloch.py"  (from qiskit.tools.visualization) line # 585:

plt.show(self.fig)

It should instead be:
plt.show()

**Comment by nonhermitian** [comment]
I cannot reproduce this issue.  Perhaps @mtreinish can give it a try.

**Comment by mtreinish** [comment]
I was not able to reproduce this either. I built a fresh virtualenv, installed qiskit 0.6.1 in it, and then copied the script from the bloch sphere tutorial and ran it. No errors and it successfully generated the visualization:

![figure_1](https://user-images.githubusercontent.com/2447371/46833248-2b3c3080-cd76-11e8-8082-05fee1ac4662.png)

My only thought is maybe the matplotlib version you have installed is out of date? @rajeshn76 which version of matplotlib do you have installed in your environment? Also which backend are you using? After taking a quick look at the matplotlib code plt.show() calls the show() method on the configured backend so it could be specific to the backend you're using.

**Comment by jaygambetta** [comment]
This i think is a matplotlib issue can you post which version you are using.  

Thanks

**Comment by nonhermitian** [comment]
We cannot reproduce this using matplotlib 3.0 or 2.2.3.
