### ISSUE TITLE
test_compiler breaks AerJob status check

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1203]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
When running the tests, the following does not work when run *after* the `test_compiler` module:

```python
backend = Aer.get_backend('qasm_simulator')
job_sim = execute(qc, backend)
job_sim.status()
```

```
Traceback (most recent call last):
  File "/Users/paul/Desktop/Github_repos/qiskit-core/test/python/test_cpp.py", line 34, in test_aer_status
    job_sim.status()
  File "/Users/paul/Desktop/Github_repos/qiskit-core/qiskit/backends/aer/aerjob.py", line 37, in _wrapper
    return func(self, *args, **kwargs)
  File "/Users/paul/Desktop/Github_repos/qiskit-core/qiskit/backends/aer/aerjob.py", line 118, in status
    self.__class__.__name__))
qiskit.backends.joberror.JobError: 'Unexpected behavior of AerJob'
```

However, if run *before* that module, it works fine.  This is true both when running locally and on Travis.  This is blocking #975.

**Comment by atilag** [comment]
I'm taking over this one
