### ISSUE TITLE
Layout error when used as initial_layout for execute()

### ISSUE THREAD

**Issue by ryan-woo** [Qiskit/qiskit-terra#1637]
### Informations

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.6.4
- **Operating system**: Mac OS 10.14

### What is the current behavior?
I generate a simple layout as in the example found in Layout.from_dict() (layout.py) docstring and then execute using the layout as the initial_layout. Use a physical backend, not a simulator.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/transpiler/_transpiler.py", line 109, in _transpilation
    pass_manager=pass_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/transpiler/_transpiler.py", line 188, in transpile_dag
    dag, coupling, initial_layout, trials=20, seed=seed_mapper)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/mapper/_mapping.py", line 397, in swap_mapper
    for k, v in initial_layout.items()}
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qiskit/mapper/_mapping.py", line 397, in <dictcomp>
    for k, v in initial_layout.items()}
TypeError: 'int' object is not subscriptable
"""
```

### Steps to reproduce the problem
```
layout_dict = {}
for qreg in quantum_regs:
    for i in range(qreg.size):
        layout_dict[(qreg, i)] = i
layout = Layout(layout_dict)
execute(quantum_circuits, backend=backend, initial_layout=layout, shots=1024)
```

### What is the expected behavior?
Execution completes successfully and the layout is respected.

### Suggested solutions
Currently the hacky solution is to respect the _mapping.py description of the initial_layout and create a Layout such as

```
layout_dict = {}
for qreg in quantum_regs:
    for i in range(qreg.size):
        layout_dict[(qreg, i)] = (qreg, i)  # Note layout_dict values are tuple.
layout = Layout(layout_dict)
execute(quantum_circuits, backend=backend, initial_layout=layout, shots=1024)
```

Perhaps _mapping.py needs to respect the Layout?

**Comment by nonhermitian** [comment]
Ok, this is because internally a `dict` of the form `dict{(reg,idx): (reg,idx)}` is expected whereas the examples given in `_layout.py` assume the values from a `dict` or `list` are simply integers. @1ucian0 changed the way the layouts are done, so I am deferring to him as to whether the `int` values are the correct to way to input, and the error is in the mapper code, or if indeed the mapper is correct, and the `Layout` object needs to be modified.

**Comment by 1ucian0** [comment]
Layout object should be maps to integers. If I remember correctly, the idea was allowing "high" level functions such as `execute` to support the object parameter and the "raw" parameter, in this case, the dict. In any case, the dict should be `dict{(reg,idx): int}`. Right @ajavadia?

I'm currently in a limited setting but, if there is no hurry, I can have a look to this in a week.

**Comment by 1ucian0** [comment]
Without running the example (so take this with a grain of salt), I noticed that the problem is "old" swap mapper which will be removed soon. Does it make sense to fix it @ajavadia?

**Comment by 1ucian0** [comment]
This issue was fixed at some point (I think, after the Layout object refactor https://github.com/Qiskit/qiskit-terra/pull/1740). In https://github.com/Qiskit/qiskit-terra/issues/1637 I added a test with the code from OP. @ryan-woo feel free to reopen if you consider that the issue is still there.

**Comment by Marco9719** [comment]
I've exactly the same problem as ryan, but my python version is 3.7.1
I've just updated qiskit to be sure that it is on the last release.
Another strange thing is that it works if I use only an index in the layout `dict`, as 
` qr = QuantumRegister(1)
layout =Layout( { (qr,0) : 1 } )`
I'm using the `ibmq_16_melbourne`  backend.
If it's useful i'll upload the whole code, but it's really the same.

**Comment by 1ucian0** [comment]
What's your qiskit-terra version?

**Comment by Marco9719** [comment]
It is the one visualized by the command `qiskit.__version__`, right?
It is 0.7.0

**Comment by 1ucian0** [comment]
The last terra version is 0.7.1. Maybe you want to update it `pip install -U qiskit-terra` and try again?

**Comment by Marco9719** [comment]
It still gives me the same error. This is the code, maybe i've done something wrong:
```
from qiskit import *
from qiskit.mapper import Layout

qr = QuantumRegister(2)
c = ClassicalRegister(2)
lay = Layout({ (qr,0): 1, (qr,1):10 })
pre = QuantumCircuit(qr, c)
pre.x(qr[0])
pre.barrier()
meas = QuantumCircuit(qr, c)
meas.measure(qr, c)
qc = pre+meas

IBMQ.load_accounts()
backend_exp = IBMQ.get_backend('ibmq_16_melbourne')

qjob = compile(qc, backend_exp, initial_layout=lay, shots=1024)
```
and gives me the error : 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-582d5d1c6d5e> in <module>
----> 1 qjob = compile(qc, backend_exp, initial_layout=lay, shots=1024)

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/tools/compiler.py in compile(circuits, backend, config, basis_gates, coupling_map, initial_layout, shots, max_credits, seed, qobj_id, skip_transpiler, seed_mapper, pass_manager, memory)
     59 
     60     circuits = transpiler.transpile(circuits, backend, basis_gates, coupling_map, initial_layout,
---> 61                                     seed_mapper, pass_manager)
     62 
     63     # step 4: Making a qobj

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in transpile(circuits, backend, basis_gates, coupling_map, initial_layout, seed_mapper, pass_manager)
     65                                          'initial_layout': initial_layout,
     66                                          'seed_mapper': seed_mapper,
---> 67                                          'pass_manager': pass_manager})
     68     if return_form_is_single:
     69         return circuits[0]

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
     91     """
     92     if len(values) == 1:
---> 93         return [task(values[0], *task_args, **task_kwargs)]
     94 
     95     Publisher().publish("terra.parallel.start", len(values))

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in _transpilation(circuit, backend, basis_gates, coupling_map, initial_layout, seed_mapper, pass_manager)
    107                               format='dag',
    108                               seed_mapper=seed_mapper,
--> 109                               pass_manager=pass_manager)
    110 
    111     out_circuit = dag_to_circuit(final_dag)

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in transpile_dag(dag, basis_gates, coupling_map, initial_layout, format, seed_mapper, pass_manager)
    186             dag = BarrierBeforeFinalMeasurements().run(dag)
    187             dag, final_layout = swap_mapper(
--> 188                 dag, coupling, initial_layout, trials=20, seed=seed_mapper)
    189             logger.info("final layout: %s", final_layout)
    190             # Expand swaps

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/mapper/_mapping.py in swap_mapper(circuit_graph, coupling_graph, initial_layout, trials, seed)
    395         device_register = QuantumRegister(coupling_graph.size(), 'q')
    396         initial_layout = {(circuit_graph.qregs[k[0]], k[1]): (device_register, v[1])
--> 397                           for k, v in initial_layout.items()}
    398         # Check the input layout
    399         circ_qubits = circuit_graph.get_qubits()

/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/mapper/_mapping.py in <dictcomp>(.0)
    395         device_register = QuantumRegister(coupling_graph.size(), 'q')
    396         initial_layout = {(circuit_graph.qregs[k[0]], k[1]): (device_register, v[1])
--> 397                           for k, v in initial_layout.items()}
    398         # Check the input layout
    399         circ_qubits = circuit_graph.get_qubits()

TypeError: 'int' object is not subscriptable
```
thanks for your support!

**Comment by 1ucian0** [comment]
can you try with master?

**Comment by Marco9719** [comment]
Sorry, but I'm quite new to this.
What do you  mean by "try with master"?
