### ISSUE TITLE
Parallel compilation gets stuck if random seed is set

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#1687]
### Informations

- **Qiskit Terra version**: 0.7
- **Python version**: 3.6
- **Operating system**: Linux

### What is the current behavior?

If `random.seed` is set, and some time afterwards `compile` is called for a set of more than one circuit: the compilation does not terminate.

When interrupted, the following appears:
```
^CTraceback (most recent call last):
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/qiskit/tools/parallel.py", line 114, in parallel_map
    item.wait(timeout=0.1)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug_set_random.py", line 18, in <module>
    basis_gates=basis_gates, shots=100)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/qiskit/tools/compiler.py", line 61, in compile
    seed_mapper, pass_manager)
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/qiskit/transpiler/_transpiler.py", line 67, in transpile
    'pass_manager': pass_manager})
  File "/opt/anaconda3/envs/YaelEnv/lib/python3.6/site-packages/qiskit/tools/parallel.py", line 123, in parallel_map
    raise QiskitError('Keyboard interrupt in parallel_map.')
qiskit.qiskiterror.QiskitError: 'Keyboard interrupt in parallel_map.'
```

### Steps to reproduce the problem

```
import random
import qiskit
import copy

random.seed = 1

qr = qiskit.QuantumRegister(2, 'qr')
qc = qiskit.QuantumCircuit(qr)

qc.h(qr[0])
qc.cx(qr[0], qr[1])

qc1 = copy.deepcopy(qc)

backend = qiskit.Aer.get_backend('qasm_simulator')
basis_gates = 'u1,u2,u3,cx'
qobj = qiskit.compile([qc, qc1], backend=backend,
                      basis_gates=basis_gates, shots=100)
```

This example runs forever.
It runs fast if the line `random.seed = 1` is removed, or if we compile only `qc` instead of `[qc, qc1]`.

**Comment by yaelbh** [comment]
Actually the correct syntax is:
```
random.seed(1)
```
And then it's OK, so I'm not sure if there is really a bug here.

**Comment by nonhermitian** [comment]
There is not, you are seeding the generator wrong:  

https://docs.python.org/3/library/random.html

Also, I doubt that that actually sets the seed of the `qasm_simulator`.  You should pass `seed=1` to compile.
