### ISSUE TITLE
Matplotlib circuit drawer raises IndexError if there is no gate in QuantumCircuit

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#1845]
### Information

- **Qiskit Terra version**: 0.7.3
- **Python version**: 3.6.8
- **Operating system**: macOS HighSierra

### What is the current behavior?

If I try to draw a quantum circuit without any gate, the mpl drawer raises IndexError. The text drawer does not have this issue.

### Steps to reproduce the problem

```
# sample.py
from qiskit import QuantumCircuit, QuantumRegister
qr = QuantumRegister(1)
qc = QuantumCircuit(qr)
print(qc)
qc.draw(filename='output.pdf', output='mpl')
```

```
$ python sample.py
         
q0_0: |0>
         
Traceback (most recent call last):
  File "c.py", line 5, in <module>
    qc.draw(filename='output.pdf', output='mpl')
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/circuit/quantumcircuit.py", line 353, in draw
    reverse_bits=reverse_bits)
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_circuit_visualization.py", line 237, in circuit_drawer
    reverse_bits=reverse_bits)
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_circuit_visualization.py", line 577, in _matplotlib_circuit_drawer
    return qcd.draw(filename)
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_matplotlib.py", line 343, in draw
    self._draw_ops(verbose)
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_matplotlib.py", line 466, in _draw_ops
    next_ops.pop(0)
IndexError: pop from empty list
```

### What is the expected behavior?

No IndexError.

### Suggested solutions

Check whether `next_ops` is empty or not.

**Comment by t-imamichi** [comment]
@nkanazawa1989 Can you check it?
