### ISSUE TITLE
Text circuit drawer raises ValueError if an empty circuit is given

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#1846]
### Information

- **Qiskit Terra version**: 0.7.3
- **Python version**: 3.6.8
- **Operating system**: macOS HighSierra

### What is the current behavior?

If I try to draw an empty circuit with the text drawer, it raises ValueError.

### Steps to reproduce the problem

```
# sample.py
from qiskit import QuantumCircuit
qc = QuantumCircuit()
print(qc)
```

```
$ python sample.py
Traceback (most recent call last):
  File "c.py", line 3, in <module>
    print(qc)
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/circuit/quantumcircuit.py", line 83, in __str__
    return str(self.draw(output='text'))
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_text.py", line 413, in __str__
    return self.single_string()
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_text.py", line 438, in single_string
    return "\n".join(self.lines())
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_text.py", line 472, in lines
    layers = self.build_layers()
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_text.py", line 672, in build_layers
    layers.append(InputWire.fillup_layer(self.wire_names(with_initial_value=True)))
  File "/Users/ima/envs/vqe2/lib/python3.6/site-packages/qiskit/tools/visualization/_text.py", line 394, in fillup_layer
    longest = max([len(name) for name in names])
ValueError: max() arg is an empty sequence
```

### What is the expected behavior?

No ValueError.

### Suggested solutions

Check whether `names` is empty or not.

**Comment by 1ucian0** [comment]
Thanks for your report @t-imamichi !

I fixed this issue in https://github.com/Qiskit/qiskit-terra/pull/1849.
