### ISSUE TITLE
ghz example is failing in qobj

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1951]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the expected behavior?
```
>>> python examples/python/ghz.py
```

```
Traceback (most recent call last):
  File "examples/python/ghz.py", line 59, in <module>
    result = job.result()
  File "/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqjob.py", line 186, in result
    job_response = self._wait_for_result(timeout=timeout, wait=wait)
  File "/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqjob.py", line 190, in _wait_for_result
    self._wait_for_submission(timeout)
  File "/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqjob.py", line 391, in _wait_for_submission
    raise self._future_captured_exception
  File "/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqjob.py", line 330, in _submit_callback
    submit_info = self._api.run_job(self._qobj_payload, backend_name=backend_name)
  File "/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/api/ibmqconnector.py", line 144, in run_job
    job = self.req.post(url, data=json.dumps(data))
  File "/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Zero' is not JSON serializable
```

Not sure what is causing this serialization error. @diego-plan9 can you take a look?

**Comment by diego-plan9** [comment]
It seems quite similar to the errors in Aer that caused two tests to be skipped during the Qobj PR (as `IBMQProvider` contains also code very similar to Aer's to deal with noise model, etc) - I'll check with @chriseclectic as they can probably be handled at the same time.

**Comment by ajavadia** [comment]
a few other examples also fail. it seems the failure happens when trying to run on devices, not Aer.

**Comment by diego-plan9** [comment]
Seems we are being too lax when handling `qobj.experiment.instructions.parameters`, and is rippling up when using types that cannot be serialized by default - will issue a PR shortly!
