### ISSUE TITLE
optimize_1q_gates unit test failures

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#1989]
Two unit test failures related to the `optimize_1q_gates` pass were uncovered while working on #1815. These were marked as `expectedFailure` since they weren't caused by the DAGNode PR, but they should be fixed.

```
======================================================================
FAIL: test_ignores_conditional_rotations (python.transpiler.test_optimize_1q_gates.TestOptimize1qGates)
Conditional rotations should not be considered in the chain.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/test/python/transpiler/test_optimize_1q_gates.py", line 145, in test_ignores_conditional_rotations
    self.assertEqual(circuit_to_dag(expected), after)
AssertionError: <qiskit.dagcircuit._dagcircuit.DAGCircuit object at 0x12d028fd0> != <qiskit.dagcircuit._dagcircuit.DAGCircuit object at 0x12d00f9e8>

Expected:
         ┌─────────┐┌─────────┐┌─────────┐
qr_0: |0>┤ U1(0.1) ├┤ U1(0.2) ├┤ U1(0.7) ├
         ├────┴────┤├────┴────┤└─────────┘
 cr_0: 0 ╡         ╞╡         ╞═══════════
         │   = 1   ││   = 3   │
 cr_1: 0 ╡         ╞╡         ╞═══════════
         └─────────┘└─────────┘
Actual:
         ┌─────────┐┌─────────┐┌─────────┐
qr_0: |0>┤ U1(0.1) ├┤ U1(0.2) ├┤ U1(0.3) ├
         ├────┴────┤├────┴────┤└─────────┘
 cr_0: 0 ╡         ╞╡         ╞═══════════
         │   = 1   ││   = 3   │
 cr_1: 0 ╡         ╞╡         ╞═══════════
         └─────────┘└─────────┘

======================================================================
FAIL: test_optimize_h_gates_pass_manager (python.transpiler.test_optimize_1q_gates.TestOptimize1qGates)
Transpile: qr:--[H]-[H]-[H]-- == qr:--[u2]--
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/test/python/transpiler/test_optimize_1q_gates.py", line 54, in test_optimize_h_gates_pass_manager
    self.assertEqual(expected, result)
AssertionError: <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x1335f5550> != <qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x12d495c18>

Expected:
         ┌──────────────┐
qr_0: |0>┤ U2(0,3.1416) ├
         └──────────────┘
Actual:
         ┌──────────────┐
qr_0: |0>┤ U2(0,3.1416) ├
         └──────────────┘
```

**Comment by maddy-tod** [comment]
I think the issue with the second test is somewhere in the pass the constant `pi` is being converted into `3.141592` so when the comparison checks if the two nodes are the same, the parameters are not considered to be equal.
