### ISSUE TITLE
Transpiling parameterized circuits for device backends raises

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2145]
```
>>> qobj = qk.compile(qc, backend=FakeTokyo())
/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/compiler.py:50: DeprecationWarning: qiskit.compile() is deprecated and will be removed in Qiskit Terra 0.9. Please use qiskit.transpile() to transform circuits and qiskit.assemble_circuits() to produce qobj.
  DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/compiler.py", line 67, in compile
    initial_layout, seed_mapper, pass_manager)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpiler.py", line 85, in transpile
    'pass_manager': pass_manager})
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/parallel.py", line 93, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpiler.py", line 143, in _transpilation
    pass_manager=pass_manager)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpiler.py", line 234, in transpile_dag
    dag = pass_manager.run_passes(dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 129, in run_passes
    dag = self._do_pass(pass_, dag, passset.options)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 169, in _do_pass
    new_dag = pass_.run(dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/optimize_1q_gates.py", line 62, in run
    left_parameters = tuple([float(x) for x in left_parameters])
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/optimize_1q_gates.py", line 62, in <listcomp>
    left_parameters = tuple([float(x) for x in left_parameters])
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/sympy/core/expr.py", line 256, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
```

**Comment by mtreinish** [comment]
I'm not sure this is going to be fixable, we switched optimize 1q gates in #1738 to resolve things numerical which resulted in a very significant speed up. If we're passing in sympy expressions for parameters which are not able to represented as a float I don't see how we can run optimize 1q on them short of adding back sympy to the pass (which I don't want to do) so that we can call simplify() in the hopes that the terms in the expressions for gates cancel don't need the undefined parameter in the expression to do the evaluation. (I'm not sure if it could provide any meaningful optimization if the parameters aren't defined though)

**Comment by ajavadia** [comment]
We need to make the transpiler be smart here and use a PassManager that does not invoke `Optimize1qGates` (or any other pass that involves numerical optimizations based on gate parameters -- another example is the `ConsolidateBlocks` pass in #2134)
