### ISSUE TITLE
Improve error message for type mismatch

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#2151]
### What is the expected enhancement?

In `qiskit/validation/base.py`, function `check_types`: if type does not match, the error message currently prints the expected type. It would help if it also prints the actual type.

**Comment by 1ucian0** [comment]
Can you write a small snippet as a minimal way to reproduce the issue? thanks!

**Comment by kdk** [comment]
```
>>> import qiskit as qk
>>> import numpy as np
>>> n = np.int64(5)
>>> qr = qk.QuantumRegister(n)
>>> qc = qk.QuantumCircuit(qr)
>>> qobj = qk.assemble_circuits(qc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/assembler.py", line 72, in assemble_circuits
    experimentconfig = QasmQobjExperimentConfig(n_qubits=n_qubits, memory_slots=memory_slots)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/validation/base.py", line 245, in _decorated
    ex.messages, ex.field_names, ex.fields, ex.data, **ex.kwargs) from None
qiskit.validation.exceptions.ModelValidationError: {'n_qubits': ["Value '5' is not the expected type <class 'int'>"]}
```

**Comment by nonhermitian** [comment]
This should actually not give a warning at all. Either the internals should work with np ints, or they should be cast to standard python ints.

**Comment by yaelbh** [comment]
Correct, for this particular example. But in the general case, where a warning should really be given, it is useful to know which wrong type is encountered.

**Comment by 1ucian0** [comment]
After #2291, the way to force the error is:
```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.compiler.assemble import assemble
import numpy as np

n = np.int64(2)
qr = QuantumRegister(n, name='q')
cr = ClassicalRegister(2, name='c')
circ = QuantumCircuit(qr, cr, name='circ')
circ.h(qr[0])
circ.cx(qr[0], qr[1])
circ.measure(qr, cr)
qr.size = n

qobj = assemble(circ, shots=2000, memory=True)
```
