### ISSUE TITLE
Error when using IBMQ.load_accounts()

### ISSUE THREAD

**Issue by vbiral** [Qiskit/qiskit-terra#2453]
### Information

- **Qiskit Terra version**: 0.8.0
- **Python version**: 3.7.1
- **Operating system**: Windows 10 x64

### What is the current behavior?
After registering for the beta version of IBM Q Experience my credentials no longer loaded using the command `IBMQ.load_accounts()`

### Steps to reproduce the problem
1. Sign in the beta version of IBM Q Experience;
2. Generate a new token at the beta version;
3. Try to load the account using: `IBMQ.load_accounts()`

### What is the expected behavior?
```
>>> from qiskit import IBMQ
>>> IBMQ.load_accounts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqprovider.py", line 199, in load_accounts
    self._append_account(credentials)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqprovider.py", line 279, in _append_account
    single_provider = IBMQSingleProvider(credentials, self)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqsingleprovider.py", line 52, in __init__
    self._api = self._authenticate(self.credentials)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqsingleprovider.py", line 103, in _authenticate
    .format(ex)) from root_exception
ConnectionError: Couldn't connect to IBMQ server: error during login: License required. You need to accept the License from Web Platform. https://quantumexperience.ng.bluemix.net

```

### Suggested solutions
I tested the following steps before I could solve the problem:
1. Accept the license using the link provided by the error;
2. Delete the accounts registered in qiskit with the command:
`IBMQ.delete_accounts()`
3. Create a second token in the beta version of IBMQ and try to load;

But this worked:
1. I went back to the old version of IBM Q Experience and noticed that my token was as "NULL".
After generating a new token, everything worked again, using the following steps in python:

```
from qiskit import IBMQ
IBMQ.delete_accounts()
IBMQ.save_account('MY-NEW_TOKEN')
IBMQ.load_accounts()

```

**Comment by ajavadia** [comment]
I think this is just a wrong error, the license should be under the new IBMQ Experience url, but that url is pointing to the old one. try here: https://quantum-computing.ibm.com/account
