### ISSUE TITLE
Decompose does not propagate bound parameters

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2482]
```
>>> import qiskit as qk
>>> p = qk.circuit.Parameter('p')
>>> qc = qk.QuantumCircuit(1)
>>> qc.rx(p,0)
<qiskit.circuit.instructionset.InstructionSet object at 0x1037b3668>
>>> inst = qc.to_instruction()
>>> qc2 = qk.QuantumCircuit(1)
>>> qc2.append(inst, [0])
<qiskit.circuit.instructionset.InstructionSet object at 0x124066710>
>>> print(qc2)
        ┌─────────────┐
q_0: |0>┤ Circuit0(p) ├
        └─────────────┘
>>> print(qc2.bind_parameters({p: 0.5}))
        ┌───────────────┐
q_0: |0>┤ Circuit0(0.5) ├
        └───────────────┘
>>> print(qc2.bind_parameters({p: 0.5}).decompose())
        ┌───────┐
q_0: |0>┤ Rx(p) ├
        └───────┘
```
In the normal workflow, this isn't an issue since we decompose before we bind, but both forms should work.

**Comment by kdk** [comment]
@chunfuchen pointed out that this also results in an error when trying to execute a circuit containing a parameterized instruction which was bound before assembly. e.g.
```
>>> import qiskit as qk
>>> theta = qk.circuit.Parameter('theta')
>>> sub_qc = qk.QuantumCircuit(2)
>>> sub_qc.h(0)
>>> sub_qc.cx(0,1)
>>> sub_qc.rz(theta)
>>> sub_qc.rz(theta, [0,1])
>>> print(sub_qc)
        ┌───┐     ┌───────────┐
q_0: |0>┤ H ├──■──┤ Rz(theta) ├
        └───┘┌─┴─┐├───────────┤
q_1: |0>─────┤ X ├┤ Rz(theta) ├
             └───┘└───────────┘
>>> sub_inst = sub_qc.to_instruction()
>>> unbound_qc = qk.QuantumCircuit(2,2)
>>> unbound_qc.append(sub_inst, [0, 1], [])
>>> unbound_qc.measure([0, 1], [0, 1])
>>> print(unbound_qc)
        ┌──────────────────┐┌─┐
q_0: |0>┤0                 ├┤M├───
        │  circuit4(theta) │└╥┘┌─┐
q_1: |0>┤1                 ├─╫─┤M├
        └──────────────────┘ ║ └╥┘
 c_0: 0 ═════════════════════╩══╬═
                                ║
 c_1: 0 ════════════════════════╩═

>>> bound_qc = unbound_qc.bind_parameters({theta: 0})
>>> bound_qc.parameters
set()
>>> qk.execute(bound_qc, backend=qk.BasicAer.get_backend('qasm_simulator'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/execute.py", line 218, in execute
    **run_config
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/assemble.py", line 147, in assemble
    run_config=run_config)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/assemble.py", line 333, in _expand_parameters
    'Circuit parameters: {}').format(all_bind_parameters, all_circuit_parameters))
qiskit.exceptions.QiskitError: 'Mismatch between run_config.parameter_binds and all circuit parameters. Parameter binds: [] Circuit parameters: [{Parameter(theta)}]'
```
