### ISSUE TITLE
TranspilerError for cu3 in cx_direction at optimization_level=2

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2570]
```
>>> qc = qk.QuantumCircuit(3, 1)
>>> qc.cu3(0,0,0,2,0)
<qiskit.circuit.instructionset.InstructionSet object at 0x125e77240>
>>> qk.transpile(qc, backend=FakeMelbourne(), optimization_level=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 147, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_configs)))
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/parallel.py", line 100, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 168, in _transpile_circuit
    return transpile_circuit(circuit, transpile_config)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpile_circuit.py", line 62, in transpile_circuit
    return pass_manager.run(circuit)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 147, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 180, in _do_pass
    new_dag = pass_.run(dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/mapping/cx_direction.py", line 81, in run
    'qubits %s and %s' % (physical_q0, physical_q1))
qiskit.transpiler.exceptions.TranspilerError: 'The circuit requires a connection between physical qubits 2 and 0'
```

**Comment by kdk** [comment]
Probably a duplicate of #2532 .
