### ISSUE TITLE
internal error from optimize_1q_gates from conditional cy gate

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2571]
```
>>> qc = qk.QuantumCircuit(2,2)
>>> qc.cy(0,1).c_if(qc.cregs[0], 0)
<qiskit.circuit.instructionset.InstructionSet object at 0x12c540160>
>>> qk.transpile(qc, backend=FakeTenerife())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 147, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_configs)))
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/parallel.py", line 100, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 168, in _transpile_circuit
    return transpile_circuit(circuit, transpile_config)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpile_circuit.py", line 62, in transpile_circuit
    return pass_manager.run(circuit)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 147, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 180, in _do_pass
    new_dag = pass_.run(dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/optimize_1q_gates.py", line 53, in run
    raise TranspilerError("internal error")
qiskit.transpiler.exceptions.TranspilerError: 'internal error'
```

**Comment by mtreinish** [comment]
It looks like this is potentially caused by an issue in `dagcircuit.collect_runs()` It's supposed to return a list of non-conditional runs of op nodes with the given names. But in the cy().c_if() example above a conditional is being returned which is triggering the if for a condition here: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimize_1q_gates.py#L50
