### ISSUE TITLE
ConsolidateBlocks raises for CX between two registers

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2806]
From https://travis-ci.com/Qiskit/qiskit-terra/jobs/216588160#L6863:

```
>>> qr1 = qk.QuantumRegister(1)
>>> qr2 = qk.QuantumRegister(2)
>>> qc = qk.QuantumCircuit(qr2, qr1, cr)
>>> qc.cx(qr1[0], qr2[1])
>>> qc.measure(qr1[0], cr[0])
>>> qk.transpile(qc, optimization_level=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 187, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_configs)))
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/tools/parallel.py", line 100, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 208, in _transpile_circuit
    return transpile_circuit(circuit, transpile_config)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/transpile_circuit.py", line 65, in transpile_circuit
    return pass_manager.run(circuit)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 171, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 202, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passmanager.py", line 215, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/consolidate_blocks.py", line 93, in run
    subcirc.append(nd.op, [q[block_index_map[i]] for i in nd.qargs])
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 359, in append
    instructions.add(self._append(instruction, qarg, carg), qarg, carg)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 382, in _append
    self._check_dups(qargs)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 438, in _check_dups
    raise QiskitError("duplicate qubit arguments")
qiskit.exceptions.QiskitError: 'duplicate qubit arguments'
```

**Comment by ajavadia** [comment]
.. and this one if you don't mind @maddy-tod  :)
