### ISSUE TITLE
qiskit doesn't import due to ChangedInMarshmallow3Warning

### ISSUE THREAD

**Issue by the-legend-of-lia** [Qiskit/qiskit-terra#2957]
### Information

- **Qiskit Terra version**: 0.9.0.dev0+1fe917b
- **Python version**: 3.7.3
- **Operating system**: Mac

### What is the current behavior?
As of this morning, import qiskit has the following stack trace:
&gt;&gt;&gt; import qiskit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lia.yeh/Documents/qiskit-terra/qiskit/__init__.py", line 23, in <module>
    from . import util
  File "/Users/lia.yeh/Documents/qiskit-terra/qiskit/util.py", line 23, in <module>
    from marshmallow.warnings import ChangedInMarshmallow3Warning
[... stack trace continues within marshmallow]

### Steps to reproduce the problem
Did this break this morning for anyone else?

### What is the expected behavior?
import qiskit succeeds

### Suggested solutions
Remove lines 23 and 56-60 of qiskit-terra/qiskit/util.py

**Comment by the-legend-of-lia** [comment]
Seems to be only when I import qiskit from command line within a directory in qiskit, so I'm closing this issue.
