### ISSUE TITLE
Inheriting from AnalysisPass as metaclass `_hash` atttribute missing

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#2974]
### Information
When inheriting from the AnalysisPass class as metaclass I get the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eddieschoute/dev/qiskit-terra/qiskit/transpiler/basepasses.py", line 30, in __call__
    pass_instance = type.__call__(cls, *args, **kwargs)
  File "/Users/eddieschoute/.pyenv/versions/3.5.7/lib/python3.5/typing.py", line 1033, in __new__
    super(GenericMeta, self).__hash__())
  File "/Users/eddieschoute/dev/qiskit-terra/qiskit/transpiler/basepasses.py", line 60, in __hash__
    return self._hash
AttributeError: type object 'Mapper' has no attribute '_hash'
```

- **Qiskit Terra version**: arct branch (close to master branch)
- **Python version**: 3.5 and 3.6
- **Operating system**: macOS

### What is the current behavior?
When running the following code on Python 3.5 or 3.6
```
import sys
from abc import ABC, abstractmethod
from typing import Generic, TypeVar, Mapping, Set, FrozenSet, List, Optional, GenericMeta
import networkx as nx
from qiskit.dagcircuit import DAGCircuit, DAGNode
from qiskit.transpiler import AnalysisPass, Layout
ArchNode = TypeVar('ArchNode')
Reg = TypeVar('Reg')
class GenericAnalysisPass(GenericMeta, AnalysisPass):
    """A superclass for the Mapper class to be able to use Generic.
    The need for this workaround was fixed in 3.7+: https://github.com/python/typing/issues/449"""
    def run(self, dag):
        raise NotImplemented("The run method was not implemented")
class Mapper(Generic[Reg, ArchNode], metaclass=GenericAnalysisPass):
    """The abstract mapper class has a mapper method that maps a circuitlayer to an architecture."""
    pass
```
I get the specified error.

I need this kind of inheritance structure because of https://github.com/python/typing/issues/449 which is only fixed in python 3.7+

### Suggested solutions
I'm not quite sure why the `_hash` attribute is set to None in the superclass of AnalysisPass. Perhaps this should be revisited?

**Comment by kdk** [comment]
Looked into this a bit with @eddieschoute . The issue was in using `AnalysisPass` as a metaclass, instead of its metaclass, `MetaPass`.
