### ISSUE TITLE
Passmanager visualizer tests fail locally

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#3283]
### Information

- **Qiskit Terra version**: Master
- **Python version**:
- **Operating system**:

### What is the current behavior?

When running the unit tests locally off of master the pass manager visualization tests always fail. The traceback:

```
==============================
Failed 2 tests - output below:
==============================

test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_basic
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/test_pass_manager_drawer.py", line 80, in test_pass_manager_drawer_basic'
    b"    self.assertFilesAreEqual(filename, path_to_diagram_reference('pass_manager_standard.dot'))"
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/visualization.py", line 46, in assertFilesAreEqual'
    b'    self.assertEqual(cur.read(), exp.read())'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 852, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual'
    b'    self.fail(self._formatMessage(msg, standardMsg))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 693, in fail'
    b'    raise self.failureException(msg)'
    b'AssertionError: \'digr[53 chars]abel="[0] FlowLinear";\\n1 [color=red, fontname[2206 chars]n}\\n\' != \'digr[53 chars]abel=FlowLinear;\\n1 [color=red, fontname=helve[2152 chars]n}\\n\''
    b'Diff is 2795 characters long. Set self.maxDiff to None to see it.'
    b''

test.python.visualization.test_pass_manager_drawer.TestPassManagerDrawer.test_pass_manager_drawer_style
-------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    b'Traceback (most recent call last):'
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/test_pass_manager_drawer.py", line 95, in test_pass_manager_drawer_style'
    b"    self.assertFilesAreEqual(filename, path_to_diagram_reference('pass_manager_style.dot'))"
    b'  File "/home/mtreinish/git/qiskit/qiskit-terra/test/python/visualization/visualization.py", line 46, in assertFilesAreEqual'
    b'    self.assertEqual(cur.read(), exp.read())'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 852, in assertEqual'
    b'    assertion_func(first, second, msg=msg)'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual'
    b'    self.fail(self._formatMessage(msg, standardMsg))'
    b'  File "/usr/lib64/python3.7/unittest/case.py", line 693, in fail'
    b'    raise self.failureException(msg)'
    b'AssertionError: \'digr[53 chars]abel="[0] FlowLinear";\\n1 [color=cyan, fontnam[2209 chars]n}\\n\' != \'digr[53 chars]abel=FlowLinear;\\n1 [color=cyan, fontname=helv[2155 chars]n}\\n\''
    b'Diff is 2798 characters long. Set self.maxDiff to None to see it.'
    b''
```

### Steps to reproduce the problem

Run tests locally

### What is the expected behavior?

The tests pass

### Suggested solutions

Either fix or remove these tests, all the image comparison tests are super flaky and provide limited value.

**Comment by mtreinish** [comment]
Looking at the reference and output images I expect that this is a graphviz version difference locally between what was used to generate the image (and what's used in CI) and the latest version 2.42.2 which I have locally. Comparing the rendered output of the dot files, the reference image is:

![reference_standard](https://user-images.githubusercontent.com/2447371/67091101-c7fb9000-f179-11e9-9083-147bdfe59d8b.png)

and the tests generate:

![current_standard](https://user-images.githubusercontent.com/2447371/67091111-ce8a0780-f179-11e9-8d92-c104be22e8b8.png)
