### ISSUE TITLE
Cannot control an opaque gate

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3565]
At 8a71143d:

```
>>> import qiskit as qk
>>> class MyGate(qk.circuit.Gate):
...   def __init__(self):
...     super().__init__("foo", 1, [])
...
>>> g = MyGate()
>>> qc = qk.QuantumCircuit(1)
>>> qc.append(g, [0])
>>> print(qc)
        ┌─────┐
q_0: |0>┤ Foo ├
        └─────┘
>>> g.control()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/gate.py", line 126, in control
    return add_control(self, num_ctrl_qubits, label)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/add_control.py", line 39, in add_control
    return control(operation, num_ctrl_qubits=num_ctrl_qubits, label=label)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/add_control.py", line 139, in control
    bgate = _unroll_gate(operation, ['u1', 'u3', 'cx'])
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/add_control.py", line 222, in _unroll_gate
    qc = dag_to_circuit(unroller.run(dag))
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/transpiler/passes/unroller.py", line 90, in run
    (str(self.basis), node.op.name))
qiskit.exceptions.QiskitError: "Cannot unroll the circuit to the given basis, ['u1', 'u3', 'cx']. No rule to expand instruction foo."
```

**Comment by ewinston** [comment]
@kdk ControlledGate doesn't support gates without definitions so probably it should raise an exception if this occurs. We could, however, just return a controlled gate with no definition.

**Comment by ajavadia** [comment]
Yeah let's return a controlled gate with no definition, num_control_qubits=1, base_gate=g.
I agree it cannot be decomposed.

**Comment by Nisha-Banerjee** [comment]
# Update for gosts_of_github_past
This issue may be solved by PR #3950 which is pending for review.

**Comment by Cryoris** [comment]
This still fails as of v2.3, unless one manually sets
```python
g.control(annotated=True)
```
#15356 paved the way to have `annotated=True` as default in a future release (currently 3.0 is in discussion) so this would work per default (and gives the compiler more opportunities for optimizations).
