### ISSUE TITLE
`schedule_circuit` fails when circuit contains measurement

### ISSUE THREAD

**Issue by georgesbarron** [Qiskit/qiskit-terra#3617]
### Information

- **Qiskit Terra version**: 0.11.0
- **Python version**: 3.7.3
- **Operating system**: macOS mojave

### What is the current behavior?

`schedule_circuit` fails to produce a `Schedule` when providing a (based on my understanding) valid `QuantumCircuit` including measurement.

```
Traceback (most recent call last):
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-33ad773855e9>", line 1, in <module>
    runfile('/Users/gbarron/Library/Preferences/PyCharm2019.2/scratches/scratch_11.py', wdir='/Users/gbarron/Library/Preferences/PyCharm2019.2/scratches')
  File "/Users/gbarron/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.6262.38/PyCharm 2019.2 EAP.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/gbarron/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/192.6262.38/PyCharm 2019.2 EAP.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/gbarron/Library/Preferences/PyCharm2019.2/scratches/scratch_11.py", line 672, in <module>
    sched_from_circ = schedule_circuit(qc, sched_config, method='asap')
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/scheduler/schedule_circuit.py", line 57, in schedule_circuit
    return methods[method](circuit, schedule_config)
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/scheduler/methods/basic.py", line 65, in as_soon_as_possible
    circ_pulse_defs = translate_gates_to_pulse_defs(circuit, schedule_config)
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/scheduler/methods/basic.py", line 199, in translate_gates_to_pulse_defs
    circ_pulse_defs.append(get_measure_schedule())
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/scheduler/methods/basic.py", line 157, in get_measure_schedule
    default_sched = inst_map.get('measure', qubits)
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/pulse/instruction_schedule_map.py", line 153, in get
    self.assert_has(instruction, qubits)
  File "/Users/gbarron/python/qiskit_stable/lib/python3.7/site-packages/qiskit/pulse/instruction_schedule_map.py", line 132, in assert_has
    qubits=self.qubits_with_instruction(instruction)))
qiskit.pulse.exceptions.PulseError: "Operation 'measure' exists, but is only defined for qubits [0]."
```

### Steps to reproduce the problem

```
from qiskit import IBMQ
from qiskit.scheduler.config import ScheduleConfig
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit import transpile
from qiskit.scheduler.schedule_circuit import schedule_circuit
import numpy as np
provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_armonk')
defaults = backend.defaults()
sched_config = ScheduleConfig(
    inst_map = defaults.circuit_instruction_map,
    meas_map = [[0,0]]
)
q = QuantumRegister(1,'q')
c = ClassicalRegister(1, 'c')
qc = QuantumCircuit(q, c)
qc.x(q[0])
qc.u1(np.pi/4, q[0])
qc.x(q[0])
qc.y(q[0])
qc.measure(q, c)
qc = transpile(qc, backend)
sched_from_circ = schedule_circuit(qc, sched_config, method='asap')
```

### What is the expected behavior?

I should be able to make a `Schedule` using `schedule_circ` with a `QuantumCircuit` that has a measurement operation. The backend (here, Armonk) has support for measurement operations.

Though perhaps I'm doing something wrong in the setup here, if that's the case I'd be interested in what I'm doing wrong.

### Suggested solutions

I think `assert_has` fails because for some reason the set of qubits for the `'measure'` instruction is `(0,0)` instead of just `0`.  https://github.com/Qiskit/qiskit-terra/blob/stable/0.11/qiskit/pulse/instruction_schedule_map.py#L111

My best guess would be that this should involve a loop over the result of `_to_tuple(qubits)` instead? But that doesn't explain why this only happens when you include the `qc.measure(q,c)` line.

**Comment by taalexander** [comment]
At a quick glance, your meas map is structured incorrectly. It should be `meas_map = [[0]]` as there is only a single qubit and its always measured on its own 😄. After changing this the code above works. 

Feel free to reopen if this does not fix your issue.
