### ISSUE TITLE
TestRandomClifford tests fail periodically in CI

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#4126]
### Information

- **Qiskit Terra version**: Master
- **Python version**: any
- **Operating system**:

### What is the current behavior?

Periodically we're seeing the TestRandomClifford tests fail in CI. For example:

```
test.python.quantum_info.operators.test_random.TestRandomClifford.test_valid_09
-------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/ddt.py", line 151, in wrapper
    return func(self, *args, **kwargs)

      File "/home/vsts/work/1/s/test/python/quantum_info/operators/test_random.py", line 170, in test_valid
    value = random_clifford(num_qubits)

      File "/home/vsts/work/1/s/qiskit/quantum_info/operators/symplectic/random.py", line 134, in random_clifford
    return Clifford(StabilizerTable(table, phase))

      File "/home/vsts/work/1/s/qiskit/quantum_info/operators/symplectic/clifford.py", line 131, in __init__
    'Invalid Clifford. Input StabilizerTable is not a valid'

    qiskit.exceptions.QiskitError: 'Invalid Clifford. Input StabilizerTable is not a valid symplectic matrix.'
```

https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=11465&view=logs&j=fad9ef03-8420-5838-ffca-3d1ed444ccc0&t=d9e59364-d4fc-590a-5492-b5319aadd598&l=4274

**Comment by chriseclectic** [comment]
I think this is due `np.linalg.inv` failing because of limited compute power on CI instance. You could fix by removing the larger qubit tests for random Clifford in the `@combine(num_qubits=[])` list.

**Comment by 1ucian0** [comment]
Im also getting some fails regularly in my local computer. I will try to capture when that happens.

**Comment by 1ucian0** [comment]
Confirmed that is not related to the CI limited power.

Since `test.python.quantum_info.operators.test_random.TestRandomClifford` is not deterministic, I will move this test out to the random suite. In the meanwhile, maybe I can find a problematic seed.

**Comment by 1ucian0** [comment]
Found a failing seed!
```python
@ddt
class TestRandomClifford(QiskitTestCase):
    """Testing random_clifford function."""

    @combine(num_qubits=[1, 2, 3, 4, 5, 10, 50, 100, 150, 211])
    def test_valid(self, num_qubits):
        """Test random_clifford {num_qubits}-qubits."""
        seed = 1587404017
        value = random_clifford(num_qubits, seed=seed)
        with self.subTest(msg='Test type'):
            self.assertIsInstance(value, Clifford)
        with self.subTest(msg='Test num_qubits'):
            self.assertEqual(value.num_qubits, num_qubits)
```
