### ISSUE TITLE
parallel map gives BrokenProcessPool error on OSX in Py38

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4401]
### Information

- **Qiskit Terra version**: master
- **Python version**: Py3.8.2
- **Operating system**: OSX

### What is the current behavior?

```python
import numpy as np
from qiskit.tools.parallel import parallel_map

def f(x):
    return np.sin(x)/2

for _ in range(10):
    parallel_map(f, np.arange(50))
```

```
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

```
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda3/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
```

**Comment by nonhermitian** [comment]
Closed as fixed by Py 3.8.3
