### ISSUE TITLE
pi_check generates to unparsable QASM

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#4717]
### Information

- **Qiskit Terra version**: master @ 2f238c917
- **Python version**: 3.5
- **Operating system**: osx

### Steps to reproduce the problem

```
>>> import qiskit as qk
>>> from math import pi
>>> qc = qk.QuantumCircuit(1)
>>> qc.u1(5*pi, 0)
>>> print(qc.qasm())
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
u1(5pi) q[0];

>>> qk.QuantumCircuit.from_qasm_str(qc.qasm())
Error near line 4 Column 10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 1614, in from_qasm_str
    return _circuit_from_qasm(qasm)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2158, in _circuit_from_qasm
    ast = qasm.parse()
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasm.py", line 56, in parse
    return qasm_p.parse(self._data)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasmparser.py", line 1072, in parse
    self.parser.parse(data, lexer=self.lexer, debug=self.parse_deb)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.5/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/qasm/qasmparser.py", line 341, in p_id_e
    + str(program[1].value) + "'")
qiskit.qasm.exceptions.QasmError: "Expected an ID, received 'pi'"
>>> from qiskit.circuit.library import *
>>> U1Gate(5*pi).qasm()
'u1(5pi)'
```

### What is the expected behavior?

Thanks to @1ucian0 for help investigating.

**Comment by obliviateandsurrender** [comment]
I think this happens because the parser doesn't recognize what to do at the recurrence of PI right after NNINTEGER. A quick fix I found for this was to add an additional regex match in the tokens for strings starting with a number and ending with "pi". Doing that little patch, it worked fine for the examples I'd tested it on. 
Something like this: https://github.com/obliviateandsurrender/qiskit-terra/commit/06d8b9122f0ec755e195391a775b4741ef63a0ad

**Comment by nonhermitian** [comment]
Perhaps modding here: https://github.com/Qiskit/qiskit-terra/blob/aa96d9e60ff2b725415f93ed4ad9ba046934b6cb/qiskit/circuit/tools/pi_check.py#L75

**Comment by albi3ro** [comment]
Since qiskit won't be the only thing needing to read the qasm, it's probably better to alter the output though `pi_check` then making reading qasm more complicated.

**Comment by albi3ro** [comment]
Can this now be closed?
