### ISSUE TITLE
Running qasm_simulator for more than 24 Qbits

### ISSUE THREAD

**Issue by gitkarma** [Qiskit/qiskit-terra#4742]
Is there a way we can run qasm_simulator for more than 24 qbits. (assuming computing and memory resources are available)

I tried to modify the file qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py  and changed the line that checks for max number of qbits.
` 
- 'n_qubits': min(24, MAX_QUBITS_MEMORY),
+ 'n_qubits': min(30, MAX_QUBITS_MEMORY)
`
But i encountered following error 

Traceback (most recent call last):
  File "/home/qc/anaconda3/envs/iiscenv/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/qc/vivek/qc/qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py", line 457, in _run_job
    result_list.append(self.run_experiment(experiment))
  File "/home/qc/vivek/qc/qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py", line 565, in run_experiment
    self._add_unitary_two(gate, qubit0, qubit1)
  File "/home/qc/vivek/qc/qiskit-terra/qiskit/providers/basicaer/qasm_simulator.py", line 163, in _add_unitary_two
    indexes = einsum_vecmul_index([qubit0, qubit1], self._number_of_qubits)
  File "/home/qc/vivek/qc/qqiskit-terra/qiskit/providers/basicaer/basicaertools.py", line 452, in einsum_vecmul_index
    number_of_qubits)
  File "/home/qc/vivek/qc/qiskit-terra/qiskit/providers/basicaer/basicaertools.py", line 488, in _einsum_matmul_index_helper
    raise QiskitError("Total number of free indexes limited to 26")
qiskit.exceptions.QiskitError: 'Total number of free indexes limited to 26'
`
qiskit-terra version 0.9.1

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP
:no_entry_sign:  We can now run qasm_simulator for values above 24 qubits if the system allows! :)

```
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, Aer

q_reg = QuantumRegister(30)
c_reg = ClassicalRegister(30)
circuit = QuantumCircuit(q_reg,c_reg)

circuit.h(q_reg)
circuit.measure(q_reg,c_reg)

circuit.draw("mpl")

backend = Aer.get_backend("qasm_simulator")
job = execute(circuit,backend, shots = 1024).result()
counts = job.get_counts()
print(counts)

```

![Screenshot_89](https://user-images.githubusercontent.com/61380731/145860086-76bc3017-9e45-4d73-b0ba-ce9987ea6ede.png)

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
Technically the original issue is still present, because BasicAer is still limited to 26 qubits, but really the solution to this is to install the full version of Qiskit Aer, so this can be closed.
