### ISSUE TITLE
Strange error while executing the Randomized Benchmarking example

### ISSUE THREAD

**Issue by ardarico** [Qiskit/qiskit-terra#4779]
### Information

- **Qiskit Terra version**: 0.14.2
- **Python version**: 3.8.3
- **Operating system**: macOS Catalina 10.15.5

### What is the current behavior?

I run the code of the Randomized Benchmarking of the qiskit-textbook in shell, not as Jupyter Notebook.
In the
for rb_seed, rb_circ_seed in enumerate(rb_circs):

loop, the execution seems to get stuck on the transpile function, with the following error messages:

Micheles-MacBook-Pro:randomized-benchmarking micheleamoretti$ python3 --version
Python 3.8.3
Micheles-MacBook-Pro:randomized-benchmarking micheleamoretti$ python3 RB.py 
Compiling seed 0
Compiling seed 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
Compiling seed 0
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/micheleamoretti/Documents/SVILUPPO/qiskit-examples/randomized-benchmarking/RB.py", line 56, in <module>
    new_rb_circ_seed = transpile(rb_circ_seed, basis_gates=basis_gates)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 134, in parallel_map
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
Compiling seed 0
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 122, in parallel_map
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    future = executor.map(_task_wrapper, param)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 674, in map
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/micheleamoretti/Documents/SVILUPPO/qiskit-examples/randomized-benchmarking/RB.py", line 56, in <module>
    new_rb_circ_seed = transpile(rb_circ_seed, basis_gates=basis_gates)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 134, in parallel_map
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 122, in parallel_map
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    results = super().map(partial(_process_chunk, fn),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in map
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    future = executor.map(_task_wrapper, param)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 674, in map
Compiling seed 0
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    results = super().map(partial(_process_chunk, fn),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    exec(code, run_globals)
  File "/Users/micheleamoretti/Documents/SVILUPPO/qiskit-examples/randomized-benchmarking/RB.py", line 56, in <module>
    self._start_queue_management_thread()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    new_rb_circ_seed = transpile(rb_circ_seed, basis_gates=basis_gates)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 134, in parallel_map
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    self._start_queue_management_thread()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 122, in parallel_map
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    future = executor.map(_task_wrapper, param)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 674, in map
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    results = super().map(partial(_process_chunk, fn),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in map
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    self._start_queue_management_thread()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    super().__init__(process_obj)
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    self._launch(process_obj)
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
  File "/Users/micheleamoretti/Documents/SVILUPPO/qiskit-examples/randomized-benchmarking/RB.py", line 56, in <module>
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
    new_rb_circ_seed = transpile(rb_circ_seed, basis_gates=basis_gates)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 134, in parallel_map
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 122, in parallel_map
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    future = executor.map(_task_wrapper, param)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 674, in map
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
    results = super().map(partial(_process_chunk, fn),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "RB.py", line 56, in <module>
    new_rb_circ_seed = transpile(rb_circ_seed, basis_gates=basis_gates)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 134, in parallel_map
    raise error
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 124, in parallel_map
    results = list(future)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Micheles-MacBook-Pro:randomized-benchmarking micheleamoretti$ 

### Steps to reproduce the problem

Unzip the attached RB.zip, you will get a RB.py file. Run it with python3.

[RB.zip](https://github.com/Qiskit/qiskit-terra/files/4959753/RB.zip)

### What is the expected behavior?

Something like:

Compiling seed 0
Simulating seed 0
After seed 0, alpha: 0.977929, EPC: 0.016553
Compiling seed 1
Simulating seed 1
After seed 1, alpha: 0.975457, EPC: 0.018407
Compiling seed 2
Simulating seed 2
After seed 2, alpha: 0.978145, EPC: 0.016391
Compiling seed 3
Simulating seed 3
After seed 3, alpha: 0.979548, EPC: 0.015339
Compiling seed 4
Simulating seed 4
After seed 4, alpha: 0.978294, EPC: 0.016280

(see https://qiskit.org/textbook/ch-quantum-hardware/randomized-benchmarking.html)

**Comment by rraymondhp** [comment]
Encountered a similar bug when running chemistry simulation.

**Comment by t-imamichi** [comment]
It may be related to this https://github.com/Qiskit/qiskit-ignis/issues/419#issuecomment-640771606

**Comment by t-imamichi** [comment]
It is fixed by #4404.

**Comment by ardarico** [comment]
I just updated qiskit to 0.20.0 and now the randomized benchmarking worrks like a charm. Thanks!

**Comment by 1ucian0** [comment]
👍
