### ISSUE TITLE
QuantumCircuit.bind/assign_parameters do not raise if passed key of invalid type

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5612]
### Information

- **Qiskit Terra version**: master @  507d3d8a95127064a6e5836d72912d965e0ad796
- **Python version**: 3.6
- **Operating system**: osx

### What is the current behavior?

```
>>> import qiskit as qk
>>> theta = qk.circuit.Parameter('theta')
>>> qc = qk.QuantumCircuit(1)
>>> qc.rx(theta, 0)
>>> qc.draw()
     ┌───────────┐
q_0: ┤ RX(theta) ├
     └───────────┘
```

Attempting to bind a Parameter not in the circuit correctly raises:
```
>>> phi = qk.circuit.Parameter('phi')
>>> qc.bind_parameters({phi: 0.1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2037, in bind_parameters
    return self.assign_parameters(value_dict)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2015, in assign_parameters
    bound_circuit._assign_parameter(parameter, value)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2061, in _assign_parameter
    for instr, param_index in self._parameter_table[parameter]:
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/parametertable.py", line 35, in __getitem__
    return self._table[key]
KeyError: Parameter(phi)
```

Likewise attempting to bind a different Parameter instance of the same name correctly raises:
```
>>> qc.bind_parameters({qk.circuit.Parameter('theta'): 0.1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2037, in bind_parameters
    return self.assign_parameters(value_dict)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2015, in assign_parameters
    bound_circuit._assign_parameter(parameter, value)
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 2061, in _assign_parameter
    for instr, param_index in self._parameter_table[parameter]:
  File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/parametertable.py", line 35, in __getitem__
    return self._table[key]
KeyError: Parameter(theta)
```

But attempting to bind using a non-Parameter type (like a string) silently passes:
```
>>> qc.bind_parameters({'theta': 0.1})
>>> qc.bind_parameters({'theta': 0.1}).draw()
     ┌───────────┐
q_0: ┤ RX(theta) ├
     └───────────┘
>>> qc.bind_parameters({None: 0.1}).draw()
     ┌───────────┐
q_0: ┤ RX(theta) ├
     └───────────┘
```

Likewise for `assign_parameters`:
```
>>> qc.assign_parameters({None: 0.1}).draw()
     ┌───────────┐
q_0: ┤ RX(theta) ├
     └───────────┘
```

### What is the expected behavior?

Even the examples above which are correctly raising, are raising from the wrong place and with the wrong error type. It's expected we catch these cases here:

https://github.com/Qiskit/qiskit-terra/blob/7e40ed1174938955235a2d9d50ce2729c17c3d3e/qiskit/circuit/quantumcircuit.py#L2010

There are tests covering these cases, but they should updated to check the type of error raised and the message:

https://github.com/Qiskit/qiskit-terra/blob/44462a8b13ea6c2cce0f9c7345c26c15fb0d4ce3/test/python/circuit/test_parameters.py#L299

**Comment by enavarro51** [comment]
I can work on this.
