### ISSUE TITLE
Run Docs of CI failed due to address collision

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#5904]
### Information

- **Qiskit Terra version**: latest
- **Python version**: NA
- **Operating system**: NA

### What is the current behavior?

I notice two issues related to CI as follows.

1. #5735 fails at CI and the message is as follows. It may be due to Sphinx parallel build.

2. When Run Docs failed, it did not terminate immediately and seemed to wait for the 1-hour time limit. Should it terminate when it fails?

```
executing qiskit.pulse.Schedule.replace
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 567, in initialize
    self.init_sockets()
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 276, in init_sockets
    self.stdin_port = self._bind_socket(self.stdin_socket, self.stdin_port)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/home/vsts/work/1/s/.tox/docs/lib/python3.7/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
...
Sphinx parallel build error:
sphinx.errors.ExtensionError: Notebook execution failed (exception: Kernel died before replying to kernel_info)
```

Full log: https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=24859&view=logs&j=23e88340-9b01-571b-4128-239215012d30&t=fd5b7ae3-9f70-5b67-b24e-b010b8098eb2

**Comment by mtreinish** [comment]
1. Yeah this is an occasional failure I've seen in the docs builds. My assumption is it is due to the parallel builds as well, but I haven't had time to debug it to confirm.

2. This is also caused by the parallel builds, it's a bug in the jupyter sphinx plugin. When the jupyter execute fails the parallel sphinx worker never reports it's status to the parent sphinx process and the parent processs sits waiting for the response from the child process forever (until we hit the 1hr job timeout). This has been a longstanding issue with jupyter execute and I've been meaning to report it upstream (but haven't found the time to create a minimal recreate to report it).

**Comment by t-imamichi** [comment]
Thank you for your information. I leave this issue for the future fix.
