### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool error when running example program

### ISSUE THREAD

**Issue by physicsnerd** [QISKit/qiskit-terra#608]
### Informations

- **QISKit (Python SDK) version**: most recent edition as of 6/28/2018
- **Python version**: 3.6.5
- **OS**: Windows

### What is the current behavior?

Run the program given below; I get the results

```
Local backends:  ['local_qasm_simulator', 'local_statevector_simulator', 'local_unitary_simulator']
Traceback (most recent call last):
  File "C:/Users/hyoung/Documents/python/qiskittest.py", line 25, in <module>
    sim_result = job_sim.result()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\qiskit\backends\local\localjob.py", line 57, in result
    return self._future.result(timeout=timeout)
  File "C:\Program Files (x86)\Python36-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files (x86)\Python36-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
>>> 
```

### Steps to reproduce the problem

Run the example program given on the main page:

```
# Import the QISKit SDK
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import available_backends, execute

# Create a Quantum Register with 2 qubits.
q = QuantumRegister(2)
# Create a Classical Register with 2 bits.
c = ClassicalRegister(2)
# Create a Quantum Circuit
qc = QuantumCircuit(q, c)

# Add a H gate on qubit 0, putting this qubit in superposition.
qc.h(q[0])
# Add a CX (CNOT) gate on control qubit 0 and target qubit 1, putting
# the qubits in a Bell state.
qc.cx(q[0], q[1])
# Add a Measure gate to see the state.
qc.measure(q, c)

# See a list of available local simulators
print("Local backends: ", available_backends({'local': True}))

# Compile and run the Quantum circuit on a simulator backend
job_sim = execute(qc, "local_qasm_simulator")
sim_result = job_sim.result()

# Show the results
print("simulation: ", sim_result)
print(sim_result.get_counts(qc))
```

### What is the expected behavior?

It should print the simulation results.

### Suggested solutions

Not really sure; this is my first time using qiskit and I was expecting the example program to just work out of the box.

**Comment by jaygambetta** [comment]
can you try this 

```python 
# Import the QISKit SDK
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import available_backends, execute

def use_example():
    # Create a Quantum Register with 2 qubits.
    q = QuantumRegister(2)
    # Create a Classical Register with 2 bits.
    c = ClassicalRegister(2)
    # Create a Quantum Circuit
    qc = QuantumCircuit(q, c)

    # Add a H gate on qubit 0, putting this qubit in superposition.
    qc.h(q[0])
    # Add a CX (CNOT) gate on control qubit 0 and target qubit 1, putting
    # the qubits in a Bell state.
    qc.cx(q[0], q[1])
    # Add a Measure gate to see the state.
    qc.measure(q, c)

    # See a list of available local simulators
    print("Local backends: ", available_backends({'local': True}))

    # Compile and run the Quantum circuit on a simulator backend
    job_sim = execute(qc, "local_qasm_simulator")
    sim_result = job_sim.result()

    # Show the results
    print("simulation: ", sim_result)
    print(sim_result.get_counts(qc))

if __name__ == "__main__":
    use_example()
```

**Comment by jaygambetta** [comment]
if it works i put a pr in to fix it as i dont have windows to check

**Comment by jaygambetta** [comment]
yeah for on windows :-(.
