### ISSUE TITLE
Import fails due to `ModuleNotFoundError: No module named 'qiskit.quantum_info.states.cython.exp_value'`

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-terra#6245]
### Information

- **Qiskit Terra version**: sources till the recent commit https://github.com/Qiskit/qiskit-terra/commit/0fc83f44a6e80969875c738b2cee7bc33223e45f
- **Python version**: Linux / Windows Python 3.9.4
- **Operating system**: Linux / Windows

### What is the current behavior?
When I import I get an error:
```
(dev-terra-new) anton@vial:~/qiskit-terra$ python
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiskit.opflow import I
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/qiskit-terra/qiskit/__init__.py", line 27, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/home/anton/qiskit-terra/qiskit/circuit/__init__.py", line 230, in <module>
    from .classicalfunction.types import Int1, Int2
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/__init__.py", line 98, in <module>
    from .classicalfunction import ClassicalFunction
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/classicalfunction.py", line 21, in <module>
    from .utils import HAS_TWEEDLEDUM
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/utils.py", line 24, in <module>
    from qiskit.circuit.library.standard_gates import (HGate, SGate, SdgGate, SwapGate, TGate, TdgGate,
  File "/home/anton/qiskit-terra/qiskit/circuit/library/__init__.py", line 378, in <module>
    from .quantum_volume import QuantumVolume
  File "/home/anton/qiskit-terra/qiskit/circuit/library/quantum_volume.py", line 18, in <module>
    from qiskit.quantum_info.random import random_unitary
  File "/home/anton/qiskit-terra/qiskit/quantum_info/__init__.py", line 122, in <module>
    from .operators import (Operator, ScalarOp, Pauli, Clifford, SparsePauliOp)
  File "/home/anton/qiskit-terra/qiskit/quantum_info/operators/__init__.py", line 18, in <module>
    from .measures import (process_fidelity,
  File "/home/anton/qiskit-terra/qiskit/quantum_info/operators/measures.py", line 28, in <module>
    from qiskit.quantum_info.states.densitymatrix import DensityMatrix
  File "/home/anton/qiskit-terra/qiskit/quantum_info/states/__init__.py", line 15, in <module>
    from .statevector import Statevector
  File "/home/anton/qiskit-terra/qiskit/quantum_info/states/statevector.py", line 34, in <module>
    from .cython.exp_value import expval_pauli_no_x, expval_pauli_with_x
ModuleNotFoundError: No module named 'qiskit.quantum_info.states.cython.exp_value'
```
The same exception on Linux/Windows.

### Steps to reproduce the problem
When I build terra from the just cloned sources via `pip install .` in a brand new clean conda environment (with `pip install -r requirements.txt`), then run python, and run `from qiskit.opflow import I` I get an exception above. Same in Linux and Windows. All good on Mac (thanks to @t-imamichi).
If I build a wheel via `python setup.py bdist_wheel` first, install terra from that wheel and then do the same, the problem disappears.

### What is the expected behavior?
No exceptions should be thrown

**Comment by mtreinish** [comment]
What exactly is your exact workflow that's having errors? Pip install on a checkout works fine for me on linux.

That being said my guess is that your issue is a python namespace thing. If you're running from the root of a checkout python doesn't know to use the installed copy in the site-packages and instead uses the `qiskit` path in the checkout for the code. If it does that then it won't have the compiled extensions because those are built by setuptools for the installed copy. If you want to run from the repo root where there is the namespace conflict you can use `python setup.py build_ext --inplace` which will compile the cython extensions in place in the repo and then python will be able to use the copy in the checkout.

**Comment by adekusar-drl** [comment]
This is what I do. `~/qiskit-terra` is the root of terra. `dev-terra-new` was a clean conda env, now it is not that clean, a few install/uninstall were run.

```
(dev-terra-new) anton@vial:~/qiskit-terra$ pip install .
Processing /home/anton/qiskit-terra
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: psutil>=5 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (5.8.0)
Requirement already satisfied: ply>=3.10 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (3.11)
Requirement already satisfied: dill>=0.3 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (0.3.3)
Requirement already satisfied: python-constraint>=1.4 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (1.4.0)
Requirement already satisfied: scipy>=1.4 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (1.6.2)
Requirement already satisfied: fastjsonschema>=2.10 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (2.15.0)
Requirement already satisfied: retworkx>=0.8.0 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (0.8.0)
Requirement already satisfied: python-dateutil>=2.8.0 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (2.8.1)
Requirement already satisfied: sympy>=1.3 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (1.8)
Requirement already satisfied: numpy>=1.17 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (1.20.2)
Requirement already satisfied: jsonschema>=2.6 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from qiskit-terra==0.18.0) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0) (0.17.3)
Requirement already satisfied: six>=1.11.0 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0) (1.15.0)
Requirement already satisfied: setuptools in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0) (56.0.0)
Requirement already satisfied: attrs>=17.4.0 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0) (20.3.0)
Requirement already satisfied: mpmath>=0.19 in /home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages (from sympy>=1.3->qiskit-terra==0.18.0) (1.2.1)
Building wheels for collected packages: qiskit-terra
  Building wheel for qiskit-terra (PEP 517) ... done
  Created wheel for qiskit-terra: filename=qiskit_terra-0.18.0-cp39-cp39-linux_x86_64.whl size=5305430 sha256=98d5a2baaa4d03fd254d34675771861694cfc18e9928de059575fc90e7a68774
  Stored in directory: /home/anton/.cache/pip/wheels/6d/c8/82/6bcb0dad0b62c327c03fb9cc23a1b2c6b3409284e9c720d024
Successfully built qiskit-terra
Installing collected packages: qiskit-terra
Successfully installed qiskit-terra-0.18.0
(dev-terra-new) anton@vial:~/qiskit-terra$ python
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiskit.opflow import I
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/qiskit-terra/qiskit/__init__.py", line 27, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/home/anton/qiskit-terra/qiskit/circuit/__init__.py", line 230, in <module>
    from .classicalfunction.types import Int1, Int2
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/__init__.py", line 98, in <module>
    from .classicalfunction import ClassicalFunction
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/classicalfunction.py", line 21, in <module>
    from .utils import HAS_TWEEDLEDUM
  File "/home/anton/qiskit-terra/qiskit/circuit/classicalfunction/utils.py", line 24, in <module>
    from qiskit.circuit.library.standard_gates import (HGate, SGate, SdgGate, SwapGate, TGate, TdgGate,
  File "/home/anton/qiskit-terra/qiskit/circuit/library/__init__.py", line 378, in <module>
    from .quantum_volume import QuantumVolume
  File "/home/anton/qiskit-terra/qiskit/circuit/library/quantum_volume.py", line 18, in <module>
    from qiskit.quantum_info.random import random_unitary
  File "/home/anton/qiskit-terra/qiskit/quantum_info/__init__.py", line 122, in <module>
    from .operators import (Operator, ScalarOp, Pauli, Clifford, SparsePauliOp)
  File "/home/anton/qiskit-terra/qiskit/quantum_info/operators/__init__.py", line 18, in <module>
    from .measures import (process_fidelity,
  File "/home/anton/qiskit-terra/qiskit/quantum_info/operators/measures.py", line 28, in <module>
    from qiskit.quantum_info.states.densitymatrix import DensityMatrix
  File "/home/anton/qiskit-terra/qiskit/quantum_info/states/__init__.py", line 15, in <module>
    from .statevector import Statevector
  File "/home/anton/qiskit-terra/qiskit/quantum_info/states/statevector.py", line 34, in <module>
    from .cython.exp_value import expval_pauli_no_x, expval_pauli_with_x
ModuleNotFoundError: No module named 'qiskit.quantum_info.states.cython.exp_value'
>>> 
```

**Comment by adekusar-drl** [comment]
The problem originally appeared in IDE, where I have project and I tried to run a script.

**Comment by mtreinish** [comment]
ok, then yeah it's exactly what I suspected earlier. Since you're running in the root of the checkout python is interpreting the `./qiskit` directory in the repository as the `qiskit` namespace for importing (this is a common trap that everyone falls into in python). You can see this in the full traceback: `"/home/anton/qiskit-terra/qiskit/quantum_info/states/statevector.py"` it is using the version in the git checkout not your pip installed version (which includes the binaries). If it were using the pip installed copy the path in the traceback would be: `/home/anton/anaconda3/envs/dev-terra-new/lib/python3.9/site-packages/qiskit` (or something like that). You can solve this 1 of 2 ways, either change your working directory to something that doesn't have `./qiskit` in the directory which will prevent the namespace conflict. Or just run `python setup.py build_ext --inplace` which will compile the extensions and put them inplace in the git repo and then when python is using the local repo instead of the pip installed version the binary is present.

**Comment by adekusar-drl** [comment]
Thanks a lot, running `python setup.py build_ext --inplace` solved the problem. And this is important to be able to run scripts from IDE with the latest changes.
So now I'm just curious, why I did not hit this issue earlier.
