### ISSUE TITLE
Allow for quasiprobabilities in plot_histogram

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6267]
### What is the expected enhancement?

We can plot quasi-probabilities in `plot_histogram`, e.g.

```
{'00000': 0.49554808799322403,
 '00001': 0.0004138725763494751,
 '00010': 0.00025370050205350114,
 '00011': 0.0030187547221223474,
 '00100': -0.0008108148662389712,
 '00101': 0.0004494630180042105,
 '00111': 0.0014731973547883487,
 '01000': -0.0017149288677695647,
 '01111': 0.00017146188264973404,
 '10000': 0.0007742930791982579,
 '10100': 0.000227104340278242,
 '10110': 0.0004658681229600881,
 '10111': 0.0005241358594717908,
 '11000': 0.0002592368447715582,
 '11001': 0.0005152694081300985,
 '11010': 0.0006157355389855065,
 '11011': -0.0007510126549324734,
 '11100': 0.005917301313087807,
 '11101': 0.00458629830963098,
 '11110': -0.0011306117467301084,
 '11111': 0.4891907657221346}
```

Currently it fails with the error:

Traceback (most recent call last):
  File "<ipython-input-10-83a9b75e21a9>", line 1, in <module>
    plot_histogram(m3_quasi)
  File "/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/visualization/counts_visualization.py", line 161, in plot_histogram
    ax.set_xticklabels(labels_dict.keys(), fontsize=14, rotation=70)
  File "/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/matplotlib/axis.py", line 1796, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/opt/miniconda3/envs/qiskit/lib/python3.9/site-packages/matplotlib/axis.py", line 1717, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (17), usually from a call to set_ticks, does not match the number of ticklabels (21).

**Comment by nonhermitian** [comment]
This will require porting the log scale histogram from Kaleidoscope as the negative values are not visible otherwise.

**Comment by jaygambetta** [comment]
I think this is going the wrong direction. Plot histogram should go towards a counts not probabilities and we should make a new plot for probabilities and we should all this. I would call it plot_quasi_probabilities and we could even overload it with taking in counts and it can normalize it so that it sums to one as well as a probabilities/quasi probability vector as you describe.

**Comment by nonhermitian** [comment]
Closing in favor of a different route.
