### ISSUE TITLE
ParameterExpression throws an error for gradients with complex coefficients.

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#6813]
### Information

- **Qiskit Terra version**: 0.18
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?

When having a `ParameterExpression` with an imaginary unit, taking a gradient w.r.t. a parameter existing in a `ParameterExpression` results in an error.

### Steps to reproduce the problem

```
p = Parameter("theta")
p2 = 1j*p
p2
Out[27]: ParameterExpression(1.0*I*theta)
p2.gradient(p)
Traceback (most recent call last):
  File "/qiskit-terra/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-058190e5d73e>", line 1, in <module>
    p2.gradient(p)
  File "/qiskit-terra/qiskit/circuit/parameterexpression.py", line 303, in gradient
    return float(expr_grad)
  File "symengine_wrapper.pyx", line 1133, in symengine.lib.symengine_wrapper.Basic.__float__
  File "symengine_wrapper.pyx", line 958, in symengine.lib.symengine_wrapper.Basic.n
  File "symengine_wrapper.pyx", line 4194, in symengine.lib.symengine_wrapper.evalf
RuntimeError: Not Implemented
```

### What is the expected behavior?

Calculating a gradient with a complex coefficient.

### Suggested solutions
Perhaps
```
  File "/qiskit-terra/qiskit/circuit/parameterexpression.py", line 303, in gradient
    return float(expr_grad)
```
should be changed to
```
  File "/qiskit-terra/qiskit/circuit/parameterexpression.py", line 303, in gradient
    return complex(expr_grad)
```
?

**Comment by enavarro51** [comment]
Perhaps it is. Seems to fix the problem. I can take this one.
