### ISSUE TITLE
"lin_comb" of Gradient framework cannot recognize parameters

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#7032]
### Information

- **Qiskit Terra version**: latest
- **Python version**: 3.9.7
- **Operating system**: Ubuntu 20.04.3

### What is the current behavior?

`Gradient('lin_comb').convert` cannot recognize parameters and raise an error while the other gradient methods 'param_shift' and 'fin_diff' can.

### Steps to reproduce the problem

```python
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes
from qiskit.opflow import CircuitStateFn
from qiskit.opflow.gradients import Gradient

ansatz = RealAmplitudes(num_qubits=1, reps=1)
for method in ['param_shift', 'fin_diff', 'lin_comb']:
    grad = Gradient(method).convert(CircuitStateFn(ansatz))
    print(f"{method} is ok")
```

output
```
param_shift is ok
fin_diff is ok
Traceback (most recent call last):
  File "/home/ima/github/qiskit/terra/tmp/lin_comb.py", line 8, in <module>
    grad = Gradient(method).convert(CircuitStateFn(ansatz))
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/gradient.py", line 71, in convert
    param_grads = [self.convert(operator, param) for param in params]
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/gradient.py", line 71, in <listcomp>
    param_grads = [self.convert(operator, param) for param in params]
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/gradient.py", line 86, in convert
    return self.get_gradient(cleaned_op, param)
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/gradient.py", line 186, in get_gradient
    return self.grad_method.convert(operator, param)
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/circuit_gradients/lin_comb.py", line 103, in convert
    return self._prepare_operator(operator, params)
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/circuit_gradients/lin_comb.py", line 231, in _prepare_operator
    return self._gradient_states(operator, target_params=params)
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/circuit_gradients/lin_comb.py", line 616, in _gradient_states
    grad_coeffs, grad_gates = self._gate_gradient_dict(gate)[idx]
  File "/home/ima/github/qiskit/terra/qiskit/opflow/gradients/circuit_gradients/lin_comb.py", line 443, in _gate_gradient_dict
    raise TypeError(f"Unrecognized parameterized gate, {gate}")
TypeError: Unrecognized parameterized gate, Instruction(name='RealAmplitudes', num_qubits=1, num_clbits=0, params=[ParameterVectorElement(θ[0]), ParameterVectorElement(θ[1])])
```

### What is the expected behavior?

No error with 'lin_comb'

**Comment by t-imamichi** [comment]
I notice that circuit library requires `decompose` for "lin_comb". The following works.
```python
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes
from qiskit.opflow import CircuitStateFn
from qiskit.opflow.gradients import Gradient

ansatz = RealAmplitudes(num_qubits=1, reps=1).decompose()
for method in ['param_shift', 'fin_diff', 'lin_comb']:
    grad = Gradient(method).convert(CircuitStateFn(ansatz))
    print(f"{method} is ok")
```
