### ISSUE TITLE
Inconsistent output in array_to_latex()

### ISSUE THREAD

**Issue by dbiersach** [Qiskit/qiskit-terra#7234]
### Information

- **Qiskit Terra version**: Qiskit Terra 0.18.3
- **Python version**: Python 3.9.7
- **Operating system**: Windows 10 (x64)

### What is the current behavior?
**array_to_latex()** does not emit consistent latex depending on the sign of a numpy array element
For example: -5.664 gets emitted as the fraction -708/125 while 5.664 is not converted to a fraction

### Steps to reproduce the problem
In a Jupyter notebook:
b = np.array(
    [
        [-5.664 - 3.623j, 7.672 - 4.470j, 1.864 - 7.149j],
        [0.766 - 4.821j, -4.413 - 0.228j, 9.759 + 4.256j],
        [1.0335 - 3.672j, 3.890 - 5.741j, 7.760 + 3.812j],
    ]
)
display(array_to_latex(b, prefix=r"\mathbf{B}="))
-5.664 is displayed as -705/125 but if the value is negated (to 5.664) it appears as 5.664 (not as a fraction)

### What is the expected behavior?
The function **_proc_value(val)** at line 60 in array.py should return the same latex output
for the floating point parameter val, independent of the sign of val

### Suggested solutions
In **qiskit-terra\qiskit\visualization\array.py** in function **_proc_value(val)**
Line #77 currently written as
	if num + denom < 20:
Line #77 should be written as 
	if abs(num) + abs(denom) < 20:
Existing code causes -5.664 to get displayed as -708/125 because num = -708, denom = 125,
thus num + denom is (-708 + 125) = -583 which is less than 20,
therefore -5.664 gets converted to the fraction -708/125
Whereas 5.664 is left as 5.664 in the returned latex string
Proposed fix uses the sum of the absolute values of num and denom, to avoid the inconsistency when val is negative

**Comment by jakelishman** [comment]
This seems like an oversight, thanks for the report!

**Comment by deeksha-singh030** [comment]
Can I work on this issue?

**Comment by jakelishman** [comment]
Sure, I'll assign you.  Let us know if you've got any questions.

**Comment by dbiersach** [comment]
Hi @deeksha-singh030 - Any success yet on implementing this fix? I'm teaching a QIS course starting January 4th - was just wondering as I am creating the slides for the class using screen shots from Qiskit. Thanks!

**Comment by deeksha-singh030** [comment]
Hello @dbiersach - I'm sorry for being this late, I've had a medical emergency. I'm continuously trying to install qiskit-terra from source but while installing developer-requirements there is an error(exit status -1 while installing scikit-learn) occurring. I've tried to update everything and all versions as per qiskit are fine in my system but not able to install. Please help me with it.

**Comment by frankharkins** [comment]
@dbiersach without testing, I think bug is probably this line, should be `abs(num) + abs(denom)`. If you have a local fork, you could try changing it and see if that fixes your problem.

https://github.com/Qiskit/qiskit-terra/blob/8e54baaab15fb8d3217c931f9ffc24b619277dd9/qiskit/visualization/array.py#L77

**Comment by frankharkins** [comment]
@deeksha-singh030 sounds like a problem with scikit-learn, do you have more information?

**Comment by deeksha-singh030** [comment]
@frankharkins error that I was getting:
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\HP\anaconda3\envs\QiskitDevenv\python.exe' 'C:\Users\HP\anaconda3\envs\QiskitDevenv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmp0260uiiy'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-s9f3kxlz\scikit-learn_2d90922b7b764b8194d880b3c7e64b6d
    Complete output (71 lines):
    Partial import of sklearn during the build process.
    C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:528: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
      warnings.warn(
    Traceback (most recent call last):
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 522, in _fallback_spawn
        yield bag
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 510, in spawn
        return super().spawn(cmd, env=env)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\ccompiler.py", line 88, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
    TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 501, in link
        self.spawn([self.linker] + ld_args)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 509, in spawn
        with self._fallback_spawn(cmd, env) as fallback:
      File "C:\Users\HP\anaconda3\envs\QiskitDevenv\lib\contextlib.py", line 153, in _exit_
        self.gen.throw(typ, value, traceback)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 531, in _fallback_spawn
        bag.value = super().spawn(cmd)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\ccompiler.py", line 88, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\ccompiler.py", line 171, in CCompiler_spawn
        raise DistutilsExecError('Command "%s" failed with exit status %d%s' %
    distutils.errors.DistutilsExecError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 objects\test_program.obj /OUT:test_program.exe" failed with exit status 1158

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\HP\anaconda3\envs\QiskitDevenv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
        main()
      File "C:\Users\HP\anaconda3\envs\QiskitDevenv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\HP\anaconda3\envs\QiskitDevenv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
        exec(compile(code, _file_, 'exec'), locals())
      File "setup.py", line 319, in <module>
        setup_package()
      File "setup.py", line 315, in setup_package
        setup(**metadata)
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 201, in configuration
        config.add_subpackage("sklearn")
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 982, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 924, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn\setup.py", line 85, in configuration
        cythonize_extensions(top_path, config)
      File "C:\Users\HP\AppData\Local\Temp\pip-install-s9f3kxlz\scikit-learn_2d90922b7b764b8194d880b3c7e64b6d\sklearn\_build_utils\_init_.py", line 47, in cythonize_extensions
        basic_check_build()
      File "C:\Users\HP\AppData\Local\Temp\pip-install-s9f3kxlz\scikit-learn_2d90922b7b764b8194d880b3c7e64b6d\sklearn\_build_utils\pre_build_helpers.py", line 113, in basic_check_build
        compile_test_program(code)
      File "C:\Users\HP\AppData\Local\Temp\pip-install-s9f3kxlz\scikit-learn_2d90922b7b764b8194d880b3c7e64b6d\sklearn\_build_utils\pre_build_helpers.py", line 76, in compile_test_program
        ccompiler.link_executable(
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\ccompiler.py", line 731, in link_executable
        self.link(CCompiler.EXECUTABLE, objects,
      File "C:\Users\HP\AppData\Local\Temp\pip-build-env-vn7kffy7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 503, in link
        raise LinkError(msg)
    distutils.errors.LinkError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 objects\test_program.obj /OUT:test_program.exe" failed with exit status 1158

**Comment by frankharkins** [comment]
@deeksha-singh030 Sorry I'm not really sure what's causing that. You could try up/downgrading python version?

**Comment by deeksha-singh030** [comment]
@frankharkins  I'm working with python 3.9.7.

**Comment by jakelishman** [comment]
Can you show the full install command for `scikit-learn`, or whatever you're installing right now?  It seems to indicate that you're trying to build `scikit-learn` from source, but that shouldn't be necessary at all - you should be able to install it by wheel.

**Comment by deeksha-singh030** [comment]
@jakelishman I was installing qiskit-terra  from source as per the commands given the qiskit documentation.

**Comment by frankharkins** [comment]
@deeksha-singh030 are you still working on this?

**Comment by deeksha-singh030** [comment]
@frankharkins I've made the required changes as suggested by @dbiersach in the issue. Please take a look on it.
 Sorry for being so late. I was trying to do this after installing qiskit-terra from source and I'm still not able to do it from source.  It would be very helpful if you could help me how to work on issues from source.
