### ISSUE TITLE
Cannot import fake backends

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#7342]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 
- **Operating system**: 

### What is happening?

Traceback (most recent call last):
  File "<ipython-input-9-1aab7f40480e>", line 2, in <module>
    backend = FakeMumbai()
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/test/mock/fake_qasm_backend.py", line 41, in __init__
    super().__init__(configuration)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/test/mock/fake_backend.py", line 57, in __init__
    super().__init__(configuration)
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/providers/backend.py", line 97, in __init__
    self._options = self._default_options()
  File "/Users/paul/Desktop/GitHub/qiskit-terra/qiskit/test/mock/fake_backend.py", line 114, in _default_options
    return aer.QasmSimulator._default_options()
AttributeError: type object 'QasmSimulator' has no attribute '_default_options'

### How can we reproduce the issue?

try to import a backend

### What should happen?

it should work

**Comment by nonhermitian** [comment]
Ahh, an unexpected dependence on Aer.

**Comment by mtreinish** [comment]
Just to clarify it's an optional dependency on aer. If you don't have aer installed it will fall back to use basic aer without issue. But if you do have aer installed you need at least aer 0.8.0 installed (which is the release which introduced the use of `BackendV1).

**Comment by nonhermitian** [comment]
I had 0.7.6 which caused it to throw the error.
