### ISSUE TITLE
`DAGCircuitError` when `if_test` is called in `for_loop` scope.

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-terra#7379]
### Environment

- **Qiskit Terra version**: 0.19.0
- **Python version**: any
- **Operating system**: any

### What is happening?

Encounter `DAGCircuitError` when `if_test` is called in `for_loop` scope.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.circuit import QuantumRegister, ClassicalRegister

qreg = QuantumRegister(4)
creg = ClassicalRegister(1)
circ = QuantumCircuit(qreg, creg)

with circ.for_loop(range(10)) as a:
    circ.ry(a, 0)
    with circ.if_test((creg, 1)):
        circ.break_loop()

print(circ)
print(circ.data[0][0].params[2]) ## qiskit.dagcircuit.exceptions.DAGCircuitError: 'invalid creg in condition for if_else'
```

```
      ┌───────────┐
q0_0: ┤0          ├
      │           │
q0_1: ┤           ├
      │           │
q0_2: ┤  For_loop ├
      │           │
q0_3: ┤           ├
      │           │
  c0: ╡0          ╞
      └───────────┘
Traceback (most recent call last):
  File "nest_error.py", line 14, in <module>
    print(circ.data[0][0].params[2])
  File "site-packages/qiskit/circuit/quantumcircuit.py", line 364, in __str__
    return str(self.draw(output="text"))
  File "site-packages/qiskit/circuit/quantumcircuit.py", line 1865, in draw
    return circuit_drawer(
  File "site-packages/qiskit/visualization/circuit_visualization.py", line 242, in circuit_drawer
    return _text_circuit_drawer(
  File "site-packages/qiskit/visualization/circuit_visualization.py", line 360, in _text_circuit_drawer
    qubits, clbits, nodes = utils._get_layered_instructions(
  File "site-packages/qiskit/visualization/utils.py", line 343, in _get_layered_instructions
    dag = circuit_to_dag(circuit)
  File "site-packages/qiskit/converters/circuit_to_dag.py", line 62, in circuit_to_dag
    dagcircuit.apply_operation_back(instruction.copy(), qargs, cargs)
  File "site-packages/qiskit/dagcircuit/dagcircuit.py", line 541, in apply_operation_back
    self._check_condition(op.name, op.condition)
  File "site-packages/qiskit/dagcircuit/dagcircuit.py", line 431, in _check_condition
    raise DAGCircuitError("invalid creg in condition for %s" % name)
qiskit.dagcircuit.exceptions.DAGCircuitError: 'invalid creg in condition for if_else'
```

### What should happen?

No error.

### Any suggestions?

None

**Comment by jakelishman** [comment]
The issue here is that the control-flow builder blocks don't track the registers that are used, only the bits, so they don't define any necessary registers in their body blocks.  We need to add tracking of these to `ControlFlowBuilderBlock`, and add them when the circuits are created to fix this.

It's a `DAGCircuitError` because the drawer tries to convert the circuit into a DAG first to get the orderings, and that's when the issue gets detected.
