### ISSUE TITLE
HAS_JAX helper does not work in unit tests

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-terra#7706]
### Environment

- **Qiskit Terra version**: sources
- **Python version**: 3.8
- **Operating system**: Mac, Windows

### What is happening?

A helper `_optionals.HAS_JAX` does not work in unit tests. An exception is thrown, see the stack trace. Outside unit tests everything looks good. Initially, an idea was to write a test that works in both cases with and without JAX installed. While this issue probably is not in Qiskit, but in JAX, I'm opening it to let you know.

Here is the stack trace:
```
(dev-terra38) ... qiskit-terra % python -m unittest test/python/test_jax_presence.py
Eavailable True
.
======================================================================
ERROR: test_jax_presence (test.python.test_jax_presence.TestJaxPresence)
test.python.test_jax_presence.TestJaxPresence.test_jax_presence
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File ".../qiskit-terra/test/python/test_jax_presence.py", line 11, in test_jax_presence
    available = bool(_optionals.HAS_JAX)
  File ".../projects/qiskit-terra/qiskit/utils/lazy_tester.py", line 114, in __bool__
    self._bool = self._is_available()
  File ".../projects/qiskit-terra/qiskit/utils/lazy_tester.py", line 289, in _is_available
    imported = importlib.import_module(module)
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jax/_src/lib/__init__.py", line 102, in <module>
    import jaxlib.pocketfft as pocketfft
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jaxlib/pocketfft.py", line 20, in <module>
    from . import pocketfft_flatbuffers_py_generated as pd
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/jaxlib/pocketfft_flatbuffers_py_generated.py", line 1, in <module>
    import flatbuffers
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/flatbuffers/__init__.py", line 15, in <module>
    from .builder import Builder
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/flatbuffers/builder.py", line 15, in <module>
    from . import number_types as N
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/flatbuffers/number_types.py", line 18, in <module>
    from . import packer
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/flatbuffers/packer.py", line 22, in <module>
    from . import compat
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/site-packages/flatbuffers/compat.py", line 19, in <module>
    import imp
  File ".../anaconda3/envs/dev-terra38/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses


----------------------------------------------------------------------
Ran 1 test in 0.033s

FAILED (errors=1)
```

### How can we reproduce the issue?

Run the test. The JAX test fails, while the matplotlib one works fine. JAX and MPL are installed.

```python
import unittest

from qiskit.test import QiskitTestCase
from qiskit.utils import optionals as _optionals


class TestJaxPresence(QiskitTestCase):
    """Main tests of approximate quantum compiler."""

    def test_jax_presence(self):
        available = bool(_optionals.HAS_JAX)
        print(f"available {available}")

    def test_mpl_presence(self):
        available = bool(_optionals.HAS_MATPLOTLIB)
        print(f"available {available}")


if __name__ == "__main__":
    unittest.main()
```

### What should happen?

No exception should be risen.

### Any suggestions?

Wait for an update in JAX?

**Comment by jakelishman** [comment]
Looks like the object is working ok, but `jax` itself (or more accurately, a dependency of `jax`) uses the `imp` module which raises a `DeprecationWarning`, and we error on unhandled warnings during test execution.

Does it similarly fail if you use it in a `@unittest.skipUnless(_optionals.HAS_JAX)` decorator?  I would expect that in that case, the tests should pass, because the `jax` import will happen during test discovery instead.

It's generally not advisable to write a test that changes its behaviour based on the environment, because it can be very hard to debug failures, and you get inconsistent coverage of the "backup" path. It'd be better to have one test that always uses the alternative (let's say Numpy), and a second test that has the `skipUnless` decorator but always uses jax if run.

**Comment by adekusar-drl** [comment]
That's right, the Qiskit code looks fine.

I added the decorator and, as you expected, the test passed. And this is a good idea, instead of having two tests in one script I can split JAX/No JAX tests into two independent scripts and the problem is solved! Thanks for the hint!
