### ISSUE TITLE
Nightly test failure log

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#7864]
This is an issue to contain tracking comments from the new nightly CI runs of the full test matrix.  Maintainers can subscribe to this issue to get notified whenever the nightly CI encounters issues.

**Comment by jakelishman** [comment]
Oversubscribed VM, nothing to worry about for us.

**Comment by jakelishman** [comment]
Oversubscribed VM again.

**Comment by jakelishman** [comment]
Oversubscribed VM - nothing to worry about.

**Comment by jakelishman** [comment]
The last five failures (while I was away on leave), numbered from oldest to newest:

1. Some sort of unlucky hang:
  ```text
  test.python.quantum_info.states.test_densitymatrix.TestDensityMatrix.test_drawings [] ... inprogress
  ```
  This was only in Windows on Python 3.10, which is also tested in the PR CI and passed. We might want to keep an eye on that, in case it happens again.

2. Oversubscribed VM.

3. A stochastic failure on the Windows Python 3.7 job:
   ```text
   test.python.algorithms.test_amplitude_estimators.TestSineIntegral.test_confidence_intervals_2
   ---------------------------------------------------------------------------------------------

   Captured traceback:
   ~~~~~~~~~~~~~~~~~~~
       Traceback (most recent call last):

         File "D:\a\1\s\test-job\lib\site-packages\ddt.py", line 191, in wrapper
       return func(self, *args, **kwargs)

         File "D:\a\1\s\test\python\algorithms\test_amplitude_estimators.py", line 412, in test_confidence_intervals
       self.assertGreater(self._statevector.time_taken, 0.0)

         File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\unittest\case.py", line 1251, in assertGreater
       self.fail(self._formatMessage(msg, standardMsg))

         File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\unittest\case.py", line 693, in fail
       raise self.failureException(msg)

       AssertionError: 0.0 not greater than 0.0
   ```

4. Strange build/install failures within matplotlib
5. Issues caused by setuptools 64.

**Comment by mtreinish** [comment]
1. When that happens it means that the test runner worker process stopped for some reason that python doesn't know about so didn't report a result status to stestr. The normal cause of this is a segfault or a similar class of errors. These can be tricky to debug in CI because we typically need extra debug information like kernel logs or a core dump which we don't typically collect.

**Comment by jakelishman** [comment]
This most recent failure is the same as point 3 in my previous comment, and I've seen it in several PR CI runs as well, so we definitely need a fix.

**Comment by jakelishman** [comment]
Oversubscribed VM.

**Comment by jakelishman** [comment]
Oversubscribed VM

**Comment by jakelishman** [comment]
Oversubscribed VM

**Comment by jakelishman** [comment]
Dodgy network link

**Comment by mtreinish** [comment]
> Nightly slow test run failed at commit [93fbc0d](https://github.com/Qiskit/qiskit-terra/commit/93fbc0d10484c459d038445c7bf9e0631cd1d329).
> 
> _Logs_: https://github.com/Qiskit/qiskit-terra/actions/runs/3529073518.

This should be fixed by #9192

**Comment by jakelishman** [comment]
VM timeout.

**Comment by jakelishman** [comment]
I've been away for a month, which is why there's a lot of errors.  All the failures to do with 62eaa5d (and several before those) are due to issues with Numpy 1.24 on the stable branch, where the Numpy fix hasn't been backported.

**Comment by jakelishman** [comment]
Ok, as of now we should be back on top of the nightly runs, after Matthew and I were away for a lot of December, and a few more things broke stable this week too.

The two most recent failures (one on main, one on stable) are because of networking issues on the Azure Linux VMs overnight, but all other tests passed.

**Comment by jakelishman** [comment]
Last two failures are VM timeout and dodgy networks, not us.

**Comment by jakelishman** [comment]
Dodgy VM/networking.

**Comment by jakelishman** [comment]
VM management issue.

**Comment by jakelishman** [comment]
The previous three comments (and probably still a couple to come) are related to #9672.

**Comment by ElePT** [comment]
> @ElePT I'm wondering why the backend primitives fail to call the bound pass manager at slow test. Do you have any idea? Your fix #9674 looks correct to me...
> 
> https://github.com/Qiskit/qiskit-terra/actions/runs/4954977087/jobs/8863956398#step:5:22086
> 
> ```
> ==============================
> Failed 2 tests - output below:
> ==============================
> 
> test.python.primitives.test_backend_estimator.TestBackendEstimator.test_bound_pass_manager
> ------------------------------------------------------------------------------------------
> 
> Captured traceback:
> ~~~~~~~~~~~~~~~~~~~
>     Traceback (most recent call last):
> 
>       File "/home/runner/work/qiskit-terra/qiskit-terra/test/python/primitives/test_backend_estimator.py", line 349, in test_bound_pass_manager
>     self.assertEqual(mock_pass.call_count, 2)
> 
>       File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/unittest/case.py", line 845, in assertEqual
>     assertion_func(first, second, msg=msg)
> 
>       File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
>     raise self.failureException(msg)
> 
>     AssertionError: 0 != 2
> 
> 
> test.python.primitives.test_backend_sampler.TestBackendSampler.test_bound_pass_manager
> --------------------------------------------------------------------------------------
> 
> Captured traceback:
> ~~~~~~~~~~~~~~~~~~~
>     Traceback (most recent call last):
> 
>       File "/home/runner/work/qiskit-terra/qiskit-terra/test/python/primitives/test_backend_sampler.py", line 401, in test_bound_pass_manager
>     self.assertEqual(mock_pass.call_count, 2)
> 
>       File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/unittest/case.py", line 845, in assertEqual
>     assertion_func(first, second, msg=msg)
> 
>       File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
>     raise self.failureException(msg)
> 
>     AssertionError: 0 != 2
> ```

I don't exactly know why it is failing, but I am thinking of other alternatives. It is particularly strange that for a while it was running fine, right? It might be related to some library update.

**Comment by t-imamichi** [comment]
I don't know when the failure started, but it might last for months. It failed at least three weeks ago. https://github.com/Qiskit/qiskit-terra/actions/runs/4782272346/jobs/8501452366#step:5:22303

**Comment by t-imamichi** [comment]
This seems the oldest failure after #9672 was merged, which happened on Mar 2.
https://github.com/Qiskit/qiskit-terra/actions/runs/4310392927/jobs/7518775522#step:5:19953

**Comment by mtreinish** [comment]
The nightly azure jobs are failing now with Python 3.12 because `pyzmq` doesn't support Python 3.12 yet and is a requirement of the jupyter stack. 

It also looks like the azure nightly jobs haven't been commenting here since the repo rename, there's probably a config issue around that.

**Comment by jakelishman** [comment]
The Azure nightly jobs use some particular path through the GitHub REST API to retrieve the correct thread to comment on and then to comment - I wouldn't be surprised if some component of that chain doesn't handle the redirects through the renaming.  Should be an easy fix, at least.
