### ISSUE TITLE
Transpilation of multiple circuits broken

### ISSUE THREAD

**Issue by JaEhr** [Qiskit/qiskit-terra#7920]
### Environment

- **Qiskit Terra version**: 0.20.0 
- **Python version**:  3.9.5

### What is happening?

When multiple circuits are submitted to the transpile command, the following error appears:
````
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Software/anaconda3/envs/qc/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Software/anaconda3/envs/qc/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in symengine.lib.symengine_wrapper.Symbol.__reduce_cython__
TypeError: self.thisptr cannot be converted to a Python object for pickling
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-20-f81f0132fe08> in <module>
      1 from qiskit import transpile
----> 2 transpile([qc]*2, backend)

/Software/anaconda3/envs/qc/lib/python3.9/site-packages/qiskit/compiler/transpiler.py in transpile(circuits, backend, basis_gates, inst_map, coupling_map, backend_properties, initial_layout, layout_method, routing_method, translation_method, scheduling_method, instruction_durations, dt, approximation_degree, timing_constraints, seed_transpiler, optimization_level, callback, output_name, unitary_synthesis_method, unitary_synthesis_plugin_config, target)
    302 
    303     # Transpile circuits in parallel
--> 304     circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
    305 
    306     end_time = time()

/Software/anaconda3/envs/qc/lib/python3.9/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    159             # Otherwise just reset parallel flag and error
    160             os.environ["QISKIT_IN_PARALLEL"] = "FALSE"
--> 161             raise error
    162 
    163         Publisher().publish("terra.parallel.finish")

/Software/anaconda3/envs/qc/lib/python3.9/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    149                 future = executor.map(_task_wrapper, param)
    150 
--> 151             results = list(future)
    152             Publisher().publish("terra.parallel.done", len(results))
    153 

/Software/anaconda3/envs/qc/lib/python3.9/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    557     careful not to keep references to yielded objects.
    558     """
--> 559     for element in iterable:
    560         element.reverse()
    561         while element:

/Software/anaconda3/envs/qc/lib/python3.9/concurrent/futures/_base.py in result_iterator()
    606                     # Careful not to keep a reference to the popped future
    607                     if timeout is None:
--> 608                         yield fs.pop().result()
    609                     else:
    610                         yield fs.pop().result(end_time - time.monotonic())

/Software/anaconda3/envs/qc/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    436                     raise CancelledError()
    437                 elif self._state == FINISHED:
--> 438                     return self.__get_result()
    439 
    440                 self._condition.wait(timeout)

/Software/anaconda3/envs/qc/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

/Software/anaconda3/envs/qc/lib/python3.9/multiprocessing/queues.py in _feed(buffer, notempty, send_bytes, writelock, close, ignore_epipe, onerror, queue_sem)
    243 
    244                         # serialize the data before acquiring the lock
--> 245                         obj = _ForkingPickler.dumps(obj)
    246                         if wacquire is None:
    247                             send_bytes(obj)

/Software/anaconda3/envs/qc/lib/python3.9/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

~/.local/lib/python3.9/site-packages/symengine/lib/symengine_wrapper.cpython-39-x86_64-linux-gnu.so in symengine.lib.symengine_wrapper.Symbol.__reduce_cython__()

TypeError: self.thisptr cannot be converted to a Python object for pickling
````

### How can we reproduce the issue?

I used the following code:

```
from qiskit.test.mock import FakeToronto
backend = FakeToronto()

from qiskit import QuantumCircuit
qc = QuantumCircuit(6)
qc.h(0)
for ii in range(qc.num_qubits-1):
    qc.cx(0,ii+1)

qc.measure_all()

from qiskit import transpile 
transpile([qc]*2, backend)
```

### What should happen?

The transpiler should transpile each circuit and return a list of transpiled circuits.

**Comment by jakelishman** [comment]
This error is strange - it looks very like an error we've previously fixed. Please could you show us the version of `symengine` you have installed?

**Comment by JaEhr** [comment]
I have symengine version 0.8.1 installed. I just saw that there is a new version released about two months ago. I will try to update and then rerun the transpilation

**Comment by mtreinish** [comment]
Yeah, this error is caused by running with symengine < 0.9.0. We raised the minimum requirement on symengine in 0.20.0 to `symengine >= 0.9`. If for some reason pip isn't handling that and upgrading symengine for you you'll face an error like this with an older version of symengine.

**Comment by JaEhr** [comment]
I just found out that there was a symengine package installed incorrectly which was not updated with the main qiskit code, thus leading to the error. now everything works fine. Thanks for your support.
