### ISSUE TITLE
Error: Cannot unroll the circuit to the given basis

### ISSUE THREAD

**Issue by prakharb10** [Qiskit/qiskit-terra#8141]
### Environment

- **Qiskit Terra version**: 0.36.2
- **Python version**: 3.8
- **Operating system**: Ubuntu 20.04

### What is happening?

Getting the following error when trying to run the circuit.

```
2022-06-06 17:02:13.475 Traceback (most recent call last):
  File "/home/friday/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/friday/Desktop/Self/QRPG/QRPG.py", line 119, in <module>
    run_job(c, pass_length)
  File "/home/friday/Desktop/Self/QRPG/QRPG.py", line 83, in run_job
    job = execute(circ, backend=bk, shots=int(sht))
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/execute.py", line 244, in execute
    experiments = transpile(experiments,
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 210, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 105, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 306, in _transpile_circuit
    return pass_manager.run(circuit, callback=transpile_config['callback'],
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 214, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 277, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 115, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 145, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 157, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/home/friday/.local/lib/python3.8/site-packages/qiskit/transpiler/passes/basis/unroller.py", line 95, in run
    raise QiskitError("Cannot unroll the circuit to the given basis, %s. "
qiskit.exceptions.QiskitError: "Cannot unroll the circuit to the given basis, ['id', 'rz', 'sx', 'x', 'cx', 'reset']. No rule to expand instruction h."
```

### How can we reproduce the issue?

A simple circuit with Hadamard gates.
```
q = QuantumRegister(5, 'q')
circuit = QuantumCircuit(q)
circuit.h(q)
circuit.measure_all()
```
The error was raised on any of the available real quantum systems.

### What should happen?

This worked fine on previous versions. Seems an error is popping up after the introduction of Unroller.
Do we need to follow some more steps before executing a circuit now?

**Comment by prakharb10** [comment]
Hey @Cryoris 
Here's the snippet for the backend selection:
```
provider = IBMQ.get_provider(hub='ibm-q')
backendd = least_busy(provider.backends(filters=lambda x: x.configuration().n_qubits >= 5
                                                              and not x.configuration().simulator
                                                              and x.status().operational == True))
```
And job execution:
```
job = execute(circ, backend=bk, shots=int(sht))
job.wait_for_final_state(callback=job_state_print)
```
Then I extract the counts and perform further processing.

Let me know if you need anything else! 😄

**Comment by jakelishman** [comment]
Could you show the output of `qiskit.__version__`?  The file names and line numbers in your original traceback don't line up with any recent version of Terra - I think something might have gone wrong with your Python environment, and you're not loading up the version you think you are.  It looks to me like you're using something from the Terra 0.16 series (originally released in late 2020), whereas your version information comment at the top of this issue says you thought you were loading Terra 0.20 (released a couple of months ago).  Perhaps a virtual environment's not loaded?

**Comment by prakharb10** [comment]
Hey @jakelishman 
You were right. The issue had something to do with the `venv` environments. For some reason, the program was referring to the base installation despite activating the venv.
Upgrading the version in the home environment fixed the issue. Apologies for the false alarm.

Closing the issue.
