### ISSUE TITLE
Qiskit Terra install fails in meson build on Ubuntu 20.04 LinuxONE

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-terra#8676]
### Environment

- **Qiskit Terra version**:  current from PyPi
- **Python version**:  Python 3.8.10
- **Operating system**:
```
linux1@ubuntu-qiskit:~$ uname -a
Linux ubuntu-qiskit 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:32:55 UTC 2022 s390x s390x s390x GNU/Linux
linux1@ubuntu-qiskit:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### What is happening?

`pip install qiskit` fails in meson build

### How can we reproduce the issue?

On LinuxONE Ubuntu 20.04 use the script [here](https://github.com/jwoehr/Quantum-Computing/blob/main/platforms/linuxone_ubuntu/install_qiskit_linuxone_ubuntu_20.04.sh) which was working 2022-07-22 and now fails as follows:
```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: /tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a
      Build dir: /tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-pl2d72u0/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
      C linker for the host machine: cc ld.bfd 2.34
      C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
      C++ linker for the host machine: c++ ld.bfd 2.34
      Host machine cpu family: s390x
      Host machine cpu: s390x
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 9.4.0 "GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.34
      Program cython found: YES (/tmp/pip-build-env-vqs5fc4f/overlay/bin/cython)
      Program pythran found: YES (/tmp/pip-build-env-vqs5fc4f/overlay/bin/pythran)
      Program cp found: YES (/usr/bin/cp)
      Program python3 found: YES (/home/linux1/Qiskit/qrel_venv/bin/python3)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Library npymath found: YES
      Library npyrandom found: NO
      Found CMake: /usr/bin/cmake (3.16.3)
      DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.
      |
      |   However, Meson was only able to find CMake 3.16.3.
      |
      |   Support for all CMake versions below 3.17.0 will be removed once
      |   newer CMake versions are more widely adopted. If you encounter
      |   any errors please try upgrading CMake to a newer version first.
      
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried cmake)
      
      ../../scipy/meson.build:130:0: ERROR: Pkg-config binary for machine 1 not found. Giving up.
      
      A full log can be found at /tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-pl2d72u0/build/meson-logs/meson-log.txt
      + meson setup --native-file=/tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/usr /tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a /tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-pl2d72u0/build
      Traceback (most recent call last):
        File "/home/linux1/Qiskit/qrel_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/linux1/Qiskit/qrel_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/linux1/Qiskit/qrel_venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 923, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 902, in _project
          with Project.with_temp_working_dir(
        File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 547, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 463, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 494, in _configure
          self._meson(
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 477, in _meson
          return self._proc('meson', *args)
        File "/tmp/pip-build-env-vqs5fc4f/overlay/lib/python3.8/site-packages/mesonpy/__init__.py", line 472, in _proc
          subprocess.check_call(list(args))
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/usr', '/tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a', '/tmp/pip-install-6fdr84_n/scipy_e6495b2e1a314f498619df61d97c118a/.mesonpy-pl2d72u0/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### What should happen?

Should build.

### Any suggestions?

@mtreinish ...help! :)

**Comment by jwoehr** [comment]
w/r/t message;

```
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried cmake)```
```
libopenblas is indeed installed.      
```
libopenblas-dev/focal-updates,now 0.3.8+ds-1ubuntu0.20.04.1 s390x [installed]
  Optimized BLAS (linear algebra) library (dev, meta)

libopenblas-pthread-dev/focal-updates,now 0.3.8+ds-1ubuntu0.20.04.1 s390x [installed,automatic]
  Optimized BLAS (linear algebra) library (dev, pthread)

libopenblas0/focal-updates,now 0.3.8+ds-1ubuntu0.20.04.1 s390x [installed,automatic]
  Optimized BLAS (linear algebra) library (meta)

libopenblas0-pthread/focal-updates,now 0.3.8+ds-1ubuntu0.20.04.1 s390x [installed,automatic]
  Optimized BLAS (linear algebra) library (shared lib, pthread)

**Comment by jakelishman** [comment]
Looks to me like it's the scipy build that's failing, not Terra - it's trying to build it from source because presumably scipy aren't supplying a wheel. I also noticed that it's failing to find `pkgconfig` - perhaps that's what it can't find the system BLAS?

**Comment by jwoehr** [comment]
Yeah, you're right @jakelishman ... this was working before, wonder why it suddenly needs the install of an rpm.
Doing some testing right now, will probably close this soon.
Thanks for jumping in ..

**Comment by jakelishman** [comment]
(Matthew's out this week, so it might be a little while til you get a response from him if you're waiting!)

**Comment by jwoehr** [comment]
Hmm, my comment was w/r/t the RHEL failure which is now fixed by installing python39-scipy via dnf.
Not sure why it changed.
Fiddling with scripts for the Ubuntu VM and trying to see what's wrong there (as I am installing the Python scipy)
Maybe wrong version.

**Comment by jwoehr** [comment]
Can't make Ubuntu do it. Was working before.
I have python3.9 installed and python3-scipy also.
Terra still tries to build scipy.
I guess Terra wants a later version of scipy than LinuxONE Ubuntu 20.04 s390x installs.

**Comment by jwoehr** [comment]
The problem I think is that Qiskit Terra wants scipy=>1.5 and s390x distros Ubuntu and SLSE don't package that yet.

**Comment by jakelishman** [comment]
Looking through the blame, that requirement was bumped in #6727 because of a problematic part of the scipy `lbfgsb` C extension in older scipys (see https://github.com/Qiskit/qiskit-terra/pull/6727#pullrequestreview-789370597).  For your purposes, would you be able to build Terra from source, and edit the requirements to allow the older scipy?  (Unless of course your purposes are just to check our builds on s390x, in which case thanks!)

**Comment by jwoehr** [comment]
I'm really checking the builds because I'm presenting this.
For that purpose I'll play with building from source.
Thanks for the pointer to the relevant PR, @jakelishman

**Comment by mtreinish** [comment]
I think this fundamentally an issue with scipy 1.9.x which changed their build system. It was trivial to build scipy <1.9 from source without the meson build system, I haven't tested what's involved to build it from source using newer versions. My guess is you can try doing something like `pip install scipy<1.9.0` and see if that build succeeds as that just worked out of the box (albeit a bit slow to compile) when I tested s390x before.

**Comment by jwoehr** [comment]
Thanks for the tip, @mtreinish ... I'll try that later this week.

**Comment by jwoehr** [comment]
@mtreinish after using `apt` to install `python3-scipy` which is at 1.3.3 I tried this:
```
(qrel) linux1@ubuntu-qiskit:~/Qiskit/qiskit-terra$ git diff
diff --git a/requirements.txt b/requirements.txt
index afe805a4e..62ca0ac0b 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -2,7 +2,7 @@ retworkx>=0.11.0
 numpy>=1.17
 ply>=3.10
 psutil>=5
-scipy>=1.5
+scipy==1.3.3
 sympy>=1.3
 dill>=0.3
 python-dateutil>=2.8.0
(qrel) linux1@ubuntu-qiskit:~/Qiskit/qiskit-terra$ pip install .
Processing /home/linux1/Qiskit/qiskit-terra
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/linux1/Qiskit/qrel/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/linux1/Qiskit/qrel/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/linux1/Qiskit/qrel/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 128, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 19, in <module>
          from setuptools_rust import Binding, RustExtension
        File "/tmp/pip-build-env-neus7lkn/overlay/lib/python3.8/site-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-neus7lkn/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jgray-19** [comment]
If you still have the most recent issue;
>       ModuleNotFoundError: No module named 'setuptools.command.build'

I found the solution here: https://github.com/MISP/misp-docker/issues/113 worked for me.

Specifically, below solved my issue:  
> sudo pip3 install setuptools-rust 
> sudo pip3 install --upgrade pip

(Currently on Ubuntu 22.04.2 LTS)

**Comment by jwoehr** [comment]
Moot at this point.
