### ISSUE TITLE
QuasiDistribution and ProbDistrobution return integer keys

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8744]
### Environment

- **Qiskit Terra version**: master
- **Python version**: 3.10
- **Operating system**: OSX

### What is happening?

The keys for `Counts` are bit-strings corresponding to observed measurement values.  However `QuasiDistribution` and `ProbDistribution` are returning int keys.

### How can we reproduce the issue?

```python
counts = {'001': 67,  '110': 113, '100': 83, '011': 205, '111': 4535, '101': 100, '010': 42, '000': 4855}
quasi = QuasiDistribution(counts)
quasi
```

gives

```python
{1: 67, 6: 113, 4: 83, 3: 205, 7: 4535, 5: 100, 2: 42, 0: 4855}
```

### What should happen?

The keys should be bit-strings as that is what is needed for computing expectation values and allows users to work with distributions in the same manner as `Counts`

**Comment by t-imamichi** [comment]
I like the idea to store keys as bitstrings. We can then handle bitstrings with blank spaces. `QuasiDistribution` currently raises an error with bitstrings with blank spaces.

```python
from qiskit.result import Counts, QuasiDistribution

counts = Counts({"0 0": 10, "1 1": 20})
print('counts', counts)

quasi = QuasiDistribution(counts)
print('quasi', quasi)
```

output
```
counts {'0 0': 10, '1 1': 20}
Traceback (most recent call last):
  File "/Users/ima/tasks/2_2022/qiskit/terra/tmp/8744.py", line 6, in <module>
    quasi = QuasiDistribution(counts)
  File "/Users/ima/envs/qiskit310/lib/python3.10/site-packages/qiskit/result/distributions/quasi.py", line 68, in __init__
    raise ValueError(
ValueError: The input keys are not a valid string format, must either be a hex string prefixed by '0x' or a binary string optionally prefixed with 0b
```

**Comment by nonhermitian** [comment]
So I talked with @mtreinish a bit about this and it is really a design decision at the end of the day.  The data is really only useful in bit-strings, but the most efficient representation is as `int`.  As the systems get larger this will become more and more important. 

Because we use `QuasiDistribution` as a generic object for both real- and true quasi-distributions one just needs to make sure that they can be used in place of `Counts` in places like visualizations etc.  That the same object can also have negative values makes that a bit more tricky though.

For mitigated `Sampler` results, the only useful thing one can do is to compute expectation values and #8748 does the casting internally, so bit-strings or not should be fine there.

**Comment by nonhermitian** [comment]
I am curious how we could still enable multiple register output from int storage though.  That seems to be nice to have for parity with `Counts`

**Comment by jlapeyre** [comment]
I'm leaning towards something like this for counts/distribution/quasi-prob distributions. (I wrote some of this in another issue, but I can't find it at the moment.)

* Python `int` to represent outcomes (keys). In some cases some kind of fixed length bit field would likely be more efficient for storage and computation. The latter might facilitate interaction with Rust and c++. (or heck, Julia). An API that hides whether it is `int` or bitfield would be good, so we are not stuck with one representation.

> The data is really only useful in bit-strings, but the most efficient representation is as `int`

* Bit operations are usually more efficient with machine integers than with binary strings or tuples. Not always. In particular, if we code strings with `1`, `0`, `Z`, `I` it's not obvious to me how to do expectation values efficiently with bitwise logical operators on integers. But, it might not be too hard to find a way. Without projecting (with `1` and `0`) IIRC I found bitwise operations on `int`s were faster for expectation values.

 > We can then handle bitstrings with blank spaces

* I guess that storing information about register sizes, for example `"1010 0101"` for two registers each of length four, is better done as meta data. This should be more efficient for storage and processing. For example outcomes `["1010 0101", "1010 0000"]` would be stored as `[165, 160]` and `reg_lengths = [4, 4]`. I also guess code would be more maintainable.

* Of course it makes sense to make the storage and code for `Counts`, `ProbDistribution`, and `QuasiDistribution` as close as possible. In fact, they can probably share quite a bit of code. There are a lot of differences currently.

* You need a bit of abstraction to make this work elegantly. In Python, it would come at a cost.

**Comment by Cryoris** [comment]
Would our own integer type, which you could convert to string (in the correct Qiskit-order 😉) solve the issue? We could store `our_int` type as key and if you want to use it as bitstring just do `our_int.to_binary()` or so?

**Comment by jlapeyre** [comment]
> our own integer type ... just do `our_int.to_binary()`

Yes, that's what I'm talking about. Something like this:
```python
class Outcome:
    def __init__(self, data):
        if isinstance(data, int):
            self._data = data
        elif isinstance(data, str):
            self._data = int(data, base=2)
        else:
            raise TypeError("Input must be int or str")

    def __repr__(self):
        return bin(self._data)[2:]

    def __str__(self): # maybe str and repr could be different
        return bin(self._data)[2:]

    def __len__(self):
        return (self._data).bit_length()

    def __int__(self):
        return self._data

    def __getitem__(self, index):
        return bool(self._data & (1 << ((self._data.bit_length()) - index - 1)))

    def __iter__(self):  # It would probably be better to use bits and avoid str.
        return (True if b == '1' else False for b in str(self))

    def __eq__(self, other): # should be faster than comparing strings.
        return self._data == other._data
```
It works like this:
```python
x = Outcome('11100001')

print("display in repl/notebook: ", x)
print("len is number of bits: ", len(x))
print("as string: ", str(x))
print("as integer: ",int(x))
print("iterate over bits: ", [bit for bit in x])
print("indexing         : ", [x[i] for i in range(len(x))])
```
with output
```python
display in repl/notebook:  11100001
len is number of bits:  8
as string:  11100001
as integer:  225
iterate over bits:  [True, True, True, False, False, False, False, True]
indexing         :  [True, True, True, False, False, False, False, True]
```

But, this is not a good solution as is. For example:
```python
In [2]: Outcome('000001')
Out[2]: 1
```
We need to store the number of bits in the outcome. But, in a container of `Outcome`s this would be wasteful and inefficient to store the same length for all outcomes, and/or compute values on the fly when you manipulate them. It may be better to store this information on the level of a collection of outcomes, for example a dictionary of counts. You could use a class containing a `dict` with `int` keys. The number of bits in the outcome (and other metadata) would be stored just once.

Trying to implement these things is instructive. Some problems arise because Python is interpreted. But, other design problems, like where to store the length, would be the same in Rust or Julia.

Looking at things like [bitstring](https://github.com/scott-griffiths/bitstring) might be useful, too.
