### ISSUE TITLE
Custom unitary gates fail in ast_to_dag.py

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#880]
The unroller is too conscious of how/where the gates are declared:

Example 1:

```
from qiskit.wrapper import load_qasm_string

qasm_string = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];

gate my_swap a,b {swap a,b;} 

my_swap q[0],q[1];
"""
circuit = load_qasm_string(qasm_string)
print(circuit.qasm())
```
Output 1:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
swap q[0],q[1];
```

Example 2:
```
from qiskit.wrapper import load_qasm_string

qasm_string = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];

swap q[0],q[1];
"""
circuit = load_qasm_string(qasm_string)
print(circuit.qasm())
```

Output 2:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
swap q[0],q[1];
```

It shouldn't matter if the gate definition is done in the body or in the library. Or please, CMV.

**Comment by delapuente** [comment]
Do you mean you expect the output for the first listing would be something like:

```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
gate my_swap a,b {swap a,b;} 
my_swap q[0],q[1];
```

I mean, do you think it should not expand the `my_swap` gate?

**Comment by ajavadia** [comment]
The `load_qasm_string()` function that you use by default unrolls to 
```
                             basis_gates="id,u0,u1,u2,u3,x,y,z,h,s,sdg,t,tdg,"
                             "rx,ry,rz,cx,cy,cz,ch,crz,cu1,cu3,swap,ccx,"
                             "cswap"
```
so it is expected that it does not keep `my_swap` in the output (not a bug).

The question is: can we get the unroller to unroll to a new basis? how do we specify that basis.

**Comment by 1ucian0** [comment]
I would expect the output to be
```
OPENQASM 2.0;
qreg q[2];
cx q[0],q[1];

**Comment by jaygambetta** [comment]
i am not clear if this is an unroller or a passer issue. To me the passer should not use the unroller and as such not need the transpiler and just be part of the parser or circuit object.

**Comment by 1ucian0** [comment]
You might be right @jaygambetta. In the current code in master:
```
>>> load_qasm_string(qasm_string, basis_gates="my_swap")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-fc31586d9084> in <module>()
----> 1 circuit = load_qasm_string(qasm_string, basis_gates="my_swap")

TypeError: load_qasm_string() got an unexpected keyword argument 'basis_gates'
```
and
```
>>> load_qasm_string(qasm_string)
qiskit/unrollers/_dagbackend.py in create_dag_op(self, name, args, qubits)
    292             op = FredkinGate(qubits[0], qubits[1], qubits[2])
    293         else:
--> 294             raise BackendError("unknown operation for name ast node name %s" % name)
    295
    296         self.circuit.add_basis_element(op.name, len(op.qargs),

BackendError: 'unknown operation for name ast node name my_swap'
```

**Comment by 1ucian0** [comment]
Indeed, `_circuit_from_qasm` calls the unroller and it seems that is not possible to define a basis there:
```
qiskit/_quantumcircuit.py in _circuit_from_qasm(qasm)
    408     from qiskit.converters import dag_to_circuit
    409     ast = qasm.parse()
--> 410     dag = Unroller(ast, DAGBackend()).execute()
    411     return dag_to_circuit(dag)
```

Maybe I should rename the issue to `_circuit_from_qasm unrolls up to standard extension`?

**Comment by 1ucian0** [comment]
The output error now is different:
```
from qiskit.wrapper import load_qasm_string

qasm_string = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];

gate my_swap a,b {swap a,b;}

my_swap q[0],q[1];
"""
circuit = load_qasm_string(qasm_string)
print(circuit.qasm())
```
```
   File "qiskit/converters/ast_to_dag.py", line 148, in _process_custom_unitary
    [self.bit_stack[-1][s] for s in gbits])
  File "qiskit/converters/ast_to_dag.py", line 376, in _create_dag_op
    raise QiskitError("unknown operation for ast node name %s" % name)
qiskit.qiskiterror.QiskitError: 'unknown operation for ast node name my_swap'
```

I suspect that the problem now is another one...  renaming the issue

**Comment by 1ucian0** [comment]
The regular update of how to reproduce this issue:
```
from qiskit import QuantumCircuit 

qasm_string = """OPENQASM 2.0; 
include "qelib1.inc"; 
qreg q[2]; 

gate my_swap a,b {swap a,b;} 

my_swap q[0],q[1]; 
""" 
circuit = QuantumCircuit.from_qasm_str(qasm_string) 
print(circuit.qasm())
```

**Comment by ajavadia** [comment]
This is the same bug as #1566
