### ISSUE TITLE
`BackendEstimator` and `BackendSampler` raise an error with a bare Aer or BasicAer simulator

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#9070]
### Environment

- **Qiskit Terra version**: main
- **Python version**: Python 3.9.15
- **Operating system**: macOS 12.6.1

### What is happening?

`BackendEstimator` and `BackendSampler` raise a following error with a bare Aer or BasicAer simulator without backend information.

```
AttributeError: Attribute max_experiments is not defined
```

### How can we reproduce the issue?

```python
from qiskit import BasicAer, Aer, QuantumCircuit
from qiskit.primitives import BackendEstimator
from qiskit.quantum_info import Pauli

qc = QuantumCircuit(1)
op = Pauli('Z')

backend = BasicAer.get_backend('qasm_simulator')
# backend = Aer.get_backend('aer_simulator')]:
est = BackendEstimator(backend=backend)
_ = est.run([qc], [op]).result()
```

```
Traceback (most recent call last):
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/providers/models/backendconfiguration.py", line 384, in __getattr__
    return self._data[name]
KeyError: 'max_experiments'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ima/tasks/2_2022/qiskit/terra/tmp/backend_estimator.py", line 11, in <module>
    _ = est.run([qc], [op]).result()
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result
    return self._future.result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 254, in _call
    result, metadata = _run_circuits(bound_circuits, self._backend, **run_options)
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 59, in _run_circuits
    max_circuits = backend.configuration().max_experiments
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/providers/models/backendconfiguration.py", line 386, in __getattr__
    raise AttributeError(f"Attribute {name} is not defined") from ex
AttributeError: Attribute max_experiments is not defined
```
--------------------------------
```python
from qiskit import BasicAer, Aer, QuantumCircuit
from qiskit.primitives import BackendSampler

qc = QuantumCircuit(1, 1)

backend = BasicAer.get_backend('qasm_simulator')
# backend = Aer.get_backend('aer_simulator')]:
est = BackendSampler(backend=backend)
_ = est.run([qc]).result()
```

```
Traceback (most recent call last):
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/providers/models/backendconfiguration.py", line 384, in __getattr__
    return self._data[name]
KeyError: 'max_experiments'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ima/tasks/2_2022/qiskit/terra/tmp/backend_sampler.py", line 9, in <module>
    _ = est.run([qc]).result()
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/primitive_job.py", line 50, in result
    return self._future.result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/backend_sampler.py", line 155, in _call
    result, _metadata = _run_circuits(bound_circuits, self._backend, **run_options)
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/primitives/backend_estimator.py", line 59, in _run_circuits
    max_circuits = backend.configuration().max_experiments
  File "/Users/ima/envs/dev39/lib/python3.9/site-packages/qiskit/providers/models/backendconfiguration.py", line 386, in __getattr__
    raise AttributeError(f"Attribute {name} is not defined") from ex
AttributeError: Attribute max_experiments is not defined
```

### What should happen?

No error

### Any suggestions?

Need to check whether `max_experiments` is available for a backend.

**Comment by t-imamichi** [comment]
#9069 fixes this issue
