### ISSUE TITLE
`NumPyEigensolver` does not support all `BaseOperator` instances.

### ISSUE THREAD

**Issue by declanmillar** [Qiskit/qiskit-terra#9091]
### Environment

- **Qiskit Terra version**: 3ce1737b
- **Python version**: 3.10.6
- **Operating system**: macOS 13.0

### What is happening?

`NumPyEigensolver` and by extension `NumPyMinimumEigensolver` do not support all `BaseOperator` instances, in particular `SparsePauliOp`. This is because it requires the `data` attribute, which `Operator` exposes but e.g. `SparsePauliOp` does not. 

### How can we reproduce the issue?

```python
from qiskit.algorithms.eigensolvers import NumPyEigensolver
from qiskit.quantum_info import SparsePauliOp

op = SparsePauliOp("Z")
npe = NumPyEigensolver()
result = npe.compute_eigenvalues(op)
```

Output:
```
Traceback (most recent call last):
  File "/Users/declanmillar/Projects/qiskit/qiskit-terra/test.py", line 10, in <module>
    result = npe.compute_eigenvalues(op)
  File "/Users/declanmillar/Projects/qiskit/qiskit-terra/qiskit/algorithms/eigensolvers/numpy_eigensolver.py", line 248, in compute_eigenvalues
    self._solve(operator)
  File "/Users/declanmillar/Projects/qiskit/qiskit-terra/qiskit/algorithms/eigensolvers/numpy_eigensolver.py", line 144, in _solve
    if operator.data.all() == operator.data.conj().T.all():
AttributeError: 'SparsePauliOp' object has no attribute 'data'
```

### What should happen?

The code should compute the eigenvalues without error, similarly to:

```python
from qiskit.algorithms.eigensolvers import NumPyEigensolver
from qiskit.quantum_info import SparsePauliOp
from qiskit.opflow import PauliSumOp

op = SparsePauliOp("Z")
op = PauliSumOp(op)
npe = NumPyEigensolver()
result = npe.compute_eigenvalues(op)
```

or:

```python
from qiskit.algorithms.eigensolvers import NumPyEigensolver
from qiskit.quantum_info import SparsePauliOp, Operator

op = SparsePauliOp("Z")
op = Operator(op.to_matrix())
npe = NumPyEigensolver()
result = npe.compute_eigenvalues(op)
```

### Any suggestions?

Generalize the computation inside `NumPyEigensolver` to avoid the `data` attribute, perhaps via `to_matrix()` or, if possible, a sparse implementation that works for `BaseOperator` instances.

**Comment by declanmillar** [comment]
I'm happy to work on this issue myself.
