### ISSUE TITLE
Running python tests on fresh clone of master fail

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#949]
### Informations

- **Qiskit Terra version**: Latest master
- **Python version**: 3.7
- **Operating system**: Linux

### What is the current behavior?

Cloning a fresh copy of qiskit-terra and running from a clean venv (with just the requirements installed) fails with the following errors from the vcr/backend tests.

```
======================================================================
ERROR: test_remote_backend_properties (python.test_backends.TestBackends)
Test backend properties.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/qiskit-terra/qiskit/backends/ibmq/ibmqprovider.py", line 85, in _authenticate
    return IBMQuantumExperience(token, config_dict, verify)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 478, in __init__
    self.req = _Request(token, config=config, verify=verify)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 253, in __init__
    ntlm_credentials=self.ntlm_credentials)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 95, in __init__
    self.obtain_token(config=self.config)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 127, in obtain_token
    **self.extra_args)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/stubs/__init__.py", line 237, in getresponse
    self.cassette.record_mode)
vcr.errors.CannotOverwriteExistingCassetteException: No match for the request (<Request (POST) https://quantumexperience.ng.bluemix.net/api/users/loginWithToken>) was found. Can't overwrite existing cassette ('/tmp/qiskit-terra/test/python/../cassettes/test_remote_backend_properties') in your current record mode ('none').

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/qiskit-terra/test/python/common.py", line 369, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/tmp/qiskit-terra/test/python/test_backends.py", line 176, in test_remote_backend_properties
    ibmq_provider = IBMQProvider(qe_token, qe_url)
  File "/tmp/qiskit-terra/qiskit/backends/ibmq/ibmqprovider.py", line 26, in __init__
    self._api = self._authenticate(token, url, proxies=proxies, verify=verify)
  File "/tmp/qiskit-terra/qiskit/backends/ibmq/ibmqprovider.py", line 93, in _authenticate
    .format(ex)) from root_exception
ConnectionError: Couldn't connect to IBMQuantumExperience server: No match for the request (<Request (POST) https://quantumexperience.ng.bluemix.net/api/users/loginWithToken>) was found. Can't overwrite existing cassette ('/tmp/qiskit-terra/test/python/../cassettes/test_remote_backend_properties') in your current record mode ('none').

======================================================================
ERROR: test_filter_status_config_dict (python.test_filter_backends.TestBackendFilters)
Test filtering by dictionary of mixed status/configuration properties
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/qiskit-terra/qiskit/backends/ibmq/ibmqbackend.py", line 161, in status
    status = self._api.backend_status(backend_name)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 866, in backend_status
    backend_type = self._check_backend(backend, 'status')
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 496, in _check_backend
    backends = self.available_backends()
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 957, in available_backends
    ret = self.req.get(url)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 354, in get
    **self.extra_args)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/stubs/__init__.py", line 237, in getresponse
    self.cassette.record_mode)
vcr.errors.CannotOverwriteExistingCassetteException: No match for the request (<Request (GET) https://quantumexperience.ng.bluemix.net/api/Backends?access_token=dummyapiusersloginWithTokenid01>) was found. Can't overwrite existing cassette ('/tmp/qiskit-terra/test/python/../cassettes/test_filter_status_config_dict') in your current record mode ('none').

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qiskit-terra/test/python/common.py", line 369, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/tmp/qiskit-terra/test/python/test_filter_backends.py", line 32, in test_filter_status_config_dict
    filtered_backends = available_backends(filter_)
  File "/tmp/qiskit-terra/qiskit/wrapper/_wrapper.py", line 173, in available_backends
    for backend in _DEFAULT_PROVIDER.available_backends(filters)]
  File "/tmp/qiskit-terra/qiskit/wrapper/defaultqiskitprovider.py", line 105, in available_backends
    backends = [instance for instance in backends
  File "/tmp/qiskit-terra/qiskit/wrapper/defaultqiskitprovider.py", line 107, in <listcomp>
    or instance.status().get(key) == value]
  File "/tmp/qiskit-terra/qiskit/backends/ibmq/ibmqbackend.py", line 180, in status
    "Couldn't get backend status: {0}".format(ex))
LookupError: Couldn't get backend status: No match for the request (<Request (GET) https://quantumexperience.ng.bluemix.net/api/Backends?access_token=dummyapiusersloginWithTokenid01>) was found. Can't overwrite existing cassette ('/tmp/qiskit-terra/test/python/../cassettes/test_filter_status_config_dict') in your current record mode ('none').

======================================================================
ERROR: test_execute_one_circuit_simulator_online (python.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test execute_one_circuit_simulator_online.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 271, in get_counts
    return self._get_experiment(circuit).counts
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 251, in _get_experiment
    return self.results[key]
KeyError: 'circuit212'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qiskit-terra/test/python/common.py", line 369, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/tmp/qiskit-terra/test/python/test_ibmq_qasm_simulator.py", line 39, in test_execute_one_circuit_simulator_online
    counts = result.get_counts(qc)
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 273, in get_counts
    raise QISKitError('No counts for circuit "{0}"'.format(circuit))
qiskit._qiskiterror.QISKitError: 'No counts for circuit "<qiskit._quantumcircuit.QuantumCircuit object at 0x7f9eff14c400>"'

======================================================================
ERROR: test_execute_several_circuits_simulator_online (python.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test execute_several_circuits_simulator_online.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 271, in get_counts
    return self._get_experiment(circuit).counts
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 251, in _get_experiment
    return self.results[key]
KeyError: 'circuit214'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qiskit-terra/test/python/common.py", line 369, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/tmp/qiskit-terra/test/python/test_ibmq_qasm_simulator.py", line 68, in test_execute_several_circuits_simulator_online
    counts2 = result.get_counts(qcr2)
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 273, in get_counts
    raise QISKitError('No counts for circuit "{0}"'.format(circuit))
qiskit._qiskiterror.QISKitError: 'No counts for circuit "<qiskit._quantumcircuit.QuantumCircuit object at 0x7f9efd098da0>"'

======================================================================
ERROR: test_online_qasm_simulator_two_registers (python.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test online_qasm_simulator_two_registers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 271, in get_counts
    return self._get_experiment(circuit).counts
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 251, in _get_experiment
    return self.results[key]
KeyError: 'circuit216'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/qiskit-terra/test/python/common.py", line 369, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/tmp/qiskit-terra/test/lib/python3.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/tmp/qiskit-terra/test/python/test_ibmq_qasm_simulator.py", line 105, in test_online_qasm_simulator_two_registers
    result2 = result.get_counts(qcr2)
  File "/tmp/qiskit-terra/qiskit/result/_result.py", line 273, in get_counts
    raise QISKitError('No counts for circuit "{0}"'.format(circuit))
qiskit._qiskiterror.QISKitError: 'No counts for circuit "<qiskit._quantumcircuit.QuantumCircuit object at 0x7f9efd08d668>"'

----------------------------------------------------------------------
Ran 453 tests in 152.374s

FAILED (errors=5, skipped=35, expected failures=1)
```

### Steps to reproduce the problem

1. `$ virtualenv3 test`
2. `$ git clone https://github.com/Qiskit/qiskit-terra.git`
3. `$ test/bin/pip install -U -r qiskit-terra/requirements.txt -r qiskit-terra/requirements-dev.txt`
4. `$ source test/bin/activate`
5. `$ cd qiskit-terra && make test`

### What is the expected behavior?

The tests pass without any errors on a fresh clone of the repo. For new developers it makes it very difficult to figure out if any potential changes are working or not if the tests don't work locally without any changes to master.

**Comment by delapuente** [comment]
Is it possible the cassetes went out of date @1ucian0?

**Comment by 1ucian0** [comment]
Sorry, took me too long to see this. Fixed in PR #1137

**Comment by mtreinish** [comment]
@1ucian0 I'm still seeing errors (on multiple machines):

```
======================================================================
ERROR: test_execute_one_circuit_simulator_online (python.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test execute_one_circuit_simulator_online.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 271, in get_counts
    return self._get_experiment(circuit).counts
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 251, in _get_experiment
    return self.results[key]
KeyError: 'circuit7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/test/python/common.py", line 373, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/opt/stack/qiskit-terra/test/python/ibmq/test_ibmq_qasm_simulator.py", line 42, in test_execute_one_circuit_simulator_online
    counts = result.get_counts(qc)
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 273, in get_counts
    raise QISKitError('No counts for circuit "{0}"'.format(circuit))
qiskit._qiskiterror.QISKitError: 'No counts for circuit "<qiskit._quantumcircuit.QuantumCircuit object at 0x7ff5ebf9c390>"'

======================================================================
ERROR: test_execute_several_circuits_simulator_online (python.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test execute_several_circuits_simulator_online.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 271, in get_counts
    return self._get_experiment(circuit).counts
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 251, in _get_experiment
    return self.results[key]
KeyError: 'circuit8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/test/python/common.py", line 373, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/opt/stack/qiskit-terra/test/python/ibmq/test_ibmq_qasm_simulator.py", line 71, in test_execute_several_circuits_simulator_online
    counts1 = result.get_counts(qcr1)
  File "/opt/stack/qiskit-terra/qiskit/result/_result.py", line 273, in get_counts
    raise QISKitError('No counts for circuit "{0}"'.format(circuit))
qiskit._qiskiterror.QISKitError: 'No counts for circuit "<qiskit._quantumcircuit.QuantumCircuit object at 0x7ff5ebf9c2b0>"'

======================================================================
ERROR: test_remote_backend_status (python.test_backends.TestBackends)
Test backend_status.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/qiskit/backends/ibmq/ibmqsingleprovider.py", line 71, in _authenticate
    credentials.verify)
  File "/usr/local/lib/python3.5/dist-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 478, in __init__
    self.req = _Request(token, config=config, verify=verify)
  File "/usr/local/lib/python3.5/dist-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 253, in __init__
    ntlm_credentials=self.ntlm_credentials)
  File "/usr/local/lib/python3.5/dist-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 95, in __init__
    self.obtain_token(config=self.config)
  File "/usr/local/lib/python3.5/dist-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 127, in obtain_token
    **self.extra_args)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/lib/python3.5/dist-packages/vcr/stubs/__init__.py", line 237, in getresponse
    self.cassette.record_mode)
vcr.errors.CannotOverwriteExistingCassetteException: No match for the request (<Request (POST) https://quantumexperience.ng.bluemix.net/api/users/loginWithToken>) was found. Can't overwrite existing cassette ('/opt/stack/qiskit-terra/test/python/../cassettes/test_remote_backend_status') in your current record mode ('none').

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/stack/qiskit-terra/test/python/common.py", line 373, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/usr/local/lib/python3.5/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/opt/stack/qiskit-terra/test/python/test_backends.py", line 95, in test_remote_backend_status
    IBMQ.enable_account(qe_token, qe_url)
  File "/opt/stack/qiskit-terra/qiskit/backends/ibmq/ibmqprovider.py", line 117, in enable_account
    self._append_account(credentials)
  File "/opt/stack/qiskit-terra/qiskit/backends/ibmq/ibmqprovider.py", line 260, in _append_account
    single_provider = IBMQSingleProvider(credentials, self)
  File "/opt/stack/qiskit-terra/qiskit/backends/ibmq/ibmqsingleprovider.py", line 36, in __init__
    self._api = self._authenticate(self.credentials)
  File "/opt/stack/qiskit-terra/qiskit/backends/ibmq/ibmqsingleprovider.py", line 79, in _authenticate
    .format(ex)) from root_exception
ConnectionError: Couldn't connect to IBMQuantumExperience server: No match for the request (<Request (POST) https://quantumexperience.ng.bluemix.net/api/users/loginWithToken>) was found. Can't overwrite existing cassette ('/opt/stack/qiskit-terra/test/python/../cassettes/test_remote_backend_status') in your current record mode ('none').
```

**Comment by 1ucian0** [comment]
Let me have another look. Thanks for checking!

**Comment by 1ucian0** [comment]
on hold, waiting for a solution in #1203

**Comment by 1ucian0** [comment]
Pending PR in #1325.
