### ISSUE TITLE
Routing pass does not account for calibrations when assessing gate direction

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-terra#9783]
### Environment

- **Qiskit Terra version**: 0.23.2
- **Python version**: 3.10.9
- **Operating system**: Fedora Linux 37

### What is happening?

When transpiling a circuit with a custom gate with a calibration, the gate direction pass does not check the circuit calibrations for the gate. It only checks the target and looks at a special-cased gates.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, pulse, transpile
from qiskit.circuit.gate import Gate
from qiskit.circuit.library import CXGate
from qiskit.transpiler import Target


# Placeholder schedule because the schedule content does not matter
sched = pulse.ScheduleBlock()
# Custom target with one two qubit gate added so that the target coupling map is connected
target = Target(num_qubits=2)
target.add_instruction(CXGate(), properties={(0, 1): None})
gate = Gate("my_2q_gate", 2, [])

circ = QuantumCircuit(2)
circ.append(gate, (0, 1))
circ.add_calibration(gate, (0, 1), sched)

transpile(circ, target=target, optimization_level=0)
```

Running this code produces:

```
Traceback (most recent call last):          
  File "/reverse.py", line 16, in <module>                                                                                                                                                           
    transpile(circ, target=target, optimization_level=1)
  File "/lib/python3.10/site-packages/qiskit/compiler/transpiler.py", line 381, in transpile
    _serial_transpile_circuit(                          
  File "/lib/python3.10/site-packages/qiskit/compiler/transpiler.py", line 474, in _serial_transpile_circuit
    result = pass_manager.run(circuit, callback=callback, output_name=output_name)
  File "/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 528, in run
    return super().run(circuits, output_name, callback)                                                                
  File "/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 228, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/lib/python3.10/site-packages/qiskit/transpiler/passmanager.py", line 283, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 125, in run
    dag = self._do_pass(pass_, dag, passset.options)                                                                   
  File "/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 173, in _do_pass
    dag = self._run_this_pass(pass_, dag)                                                                              
  File "/lib/python3.10/site-packages/qiskit/transpiler/runningpassmanager.py", line 202, in _run_this_pass
    new_dag = pass_.run(dag)                       
  File "/lib/python3.10/site-packages/qiskit/transpiler/passes/utils/gate_direction.py", line 300, in run
    return self._run_target(dag, layout_map)
  File "/lib/python3.10/site-packages/qiskit/transpiler/passes/utils/gate_direction.py", line 270, in _run_target
    raise TranspilerError(
qiskit.transpiler.exceptions.TranspilerError: "Flipping of gate direction is only supported for ['cx', 'cz', 'ecr'] at this time, not 'my_2q_gate'."
```

### What should happen?

Transpilation should run without error. It should leave the circuit unmodified.

### Any suggestions?

In `gate_direction.py`, right before/after the target is checked in `_run_target`, the circuit's calibrations should be checked for the gate and no exception should be raised if the calibration is there.

Additionally, there may be an additional bug here because the error message is confusingly about flipping the gate direction when the calibration has the right direction present. A "gate not found" type of message would be more appropriate. I wonder if there are other ways to trigger the "flipping the gate" message where the issue is that the gate was not found at all.

This issue was first noticed in the [qiskit-dynamics PR](https://github.com/Qiskit/qiskit-dynamics/pull/193#discussion_r1126753960) for the DynamicsBackend tutorial. In most cases, we are working only with gates already in the Target so this issue does not come up.

**Comment by nkanazawa1989** [comment]
Probably we could copy added calibrations to target in the running pass manager, which might be easiest fix. Alternatively, we could update every pass to check calibration -- so far calibration was ignored in many places and we needed to manually update basis gates to respect added calibration. 

Target must be copied through serialization so mutating the target per circuit doesn't trigger race condition.
https://github.com/Qiskit/qiskit-terra/blob/2ce129a14279a746d309f00e311b930ddbfe633c/qiskit/transpiler/passmanager.py#L264-L266

**Comment by jakelishman** [comment]
I've made #9786 to address the bulk of this issue.  For the error messages:
- when running in `CouplingMap` mode, the pass can't know if an instruction is actually supported or not, so the "flipping of gate direction" thing is the right call - it's up to translation passes to sort that stuff out first
- agreed that the transpiler error messages can be confusing; if a gate isn't supported in the flipped direction either, we should say that rather than saying "we don't know how to flip this gate".

**Comment by jakelishman** [comment]
I've also made #9787 to address the error-message concerns of this issue.

**Comment by nkanazawa1989** [comment]
Yes, that sounds reasonable. PR also looks good to me. Thanks Jake.
